== 8. AJAX

=== 8.1. Using AJAX sources

DataTables has the ability to read data from virtually any JSON data source that can be obtained by AJAX.

It can be useful to populate a table using an AJAX source, e.g. using a web service that returns a list of objects.

Since v0.8.2, Dandelion-Datatables support AJAX sources. But be aware, even if the data is obtained from the server via an AJAX call, DataTables will process it client-side, as for classic DOM sources. So this may be not suitable for large data sets. In this latter case, you should consider using the <<8-4-server-side-processing, server-side processing>> instead.

WARNING: Note that depending on the data source type (DOM, AJAX), some attributes of the JSP taglib or the Thymeleaf dialect may be available or not. That's why you can see a particular column called "Data source compatibility" in all tag references.

==== 8.1.1. How to use an AJAX source

[discrete]
===== Using JSP

Instead of using the <<jsp-table-data, `data`>> table attribute (used for DOM sources), use the <<jsp-table-data, `url`>> table attribute instead. 

[source, xml]
----
<datatables:table id="myTableId" url="/persons"> <1>
  <datatables:column title="Id" property="id" /> <2>
  <datatables:column title="FirstName" property="firstName" /> <2>
  <datatables:column title="LastName" property="lastName" /> <2>
  <datatables:column title="City" property="address.town.name" /> <2>
  <datatables:column title="Mail" property="mail" /> <2>
</datatables:table>
----
<1> Dandelion-Datatables will automatically modify the provided URL by prepending the context path
<2> The <<jsp-column-property, `property`>> column attribute is used for both DOM and AJAX sources

[discrete]
===== Using Thymeleaf

Using Thymeleaf, you have to fill in the <<tml-table-url, `dt:url`>> table attribute. The same rules apply as for JSP regarding the value you set.

Moreover, you have to tell Dandelion-datatables which property must be read from the JSON source for each column using the <<tml-th-property, `dt:property`>> attribute.

[source, xml]
----
<table id="myTableId" dt:table="true" dt:url="@{/persons}"> <1>
  <thead>
    <tr>
      <th dt:property="id">Id</th> <2>
      <th dt:property="firstName">Firstname</th> <2>
      <th dt:property="lastName">Lastname</th> <2>
      <th dt:property="address.town.name">City</th> <2>
      <th dt:property="mail">Mail</th> <2>
    </tr>
  </thead>
</table>
----
<1> Don't forget to use the Thymeleaf "at" syntax: `@{/some-url}`
<2> You need to specify each property to display using the <<tml-th-property, `dt:property`>> th attribute

WARNING: Cross-domain requests are not supported yet.

==== 8.1.2. Example using Spring

The Spring @Controller bellow contains a RESTful method `findAll` that returns a list of `Person` as raw data using the `@ResponseBody` annotation.

[source, java]
----
@Controller
@RequestMapping(method = RequestMethod.GET)
public class SpringMvcAjaxController {

  @Autowired
  private PersonService personService;

  @RequestMapping(value = "/persons")
  public @ResponseBody List<Person> findAll(HttpServletRequest request) {
    return personService.fin8.3.dAll();
  }
}
----

NOTE: Note that since Spring defaultly performs the JSON serialization using the Jackson JSON processor, make sure to have the http://search.maven.org/#search%7Cga%7C1%7Cjackson-mapper-asl[Jackson JARs] in your classpath to make it work.

=== 8.2. Customizing AJAX calls

You may need some additional request parameters to call your AJAX source or even a fully customized call. Well, whether or not you use server-side processing, you can completely override the default AJAX request which obtains the data from the server to something more suitable for your application.
  
In order to be fully customizable, Dandelion-Datatables wraps the http://datatables.net/reference/option/ajax[object mode of operation]. This means you need to provide the `jQuery.ajax` syntax. For example, assuming the following bundle:

.dandelion/ajax.json
[source, json]
----
{
  "assets": [
    {
      "locations": {
        "webapp": "/assets/js/ajax.js"
      }
    }
  ]
}
----

Which contains the following JavaScript file:

.assets/js/ajax.js
[source, javascript]
----
function customAjaxParams(){
  return {
    "type" : "POST",
    "data" : { name: "John", location: "Boston" }
  };
}
----  

[discrete]
==== Using JSP   

Use the <<jsp-table-ajaxParam, `ajaxParam` >> table attribute as follows:

[source, xml]
----
<datatables:table id="myTableId" url="/ajax/persons-via-post" serverSide="true" ajaxParams="ajax#customAjaxParams"> <1>
  ...
</datatables:table>
----
<1> You can use the <<14-3-bundle-special-syntax, bundle special syntax>> to automatically include one (ore more) bundle(s)

[discrete]
==== Using Thymeleaf

Use the <<tml-table-ajaxParams, `dt:ajaxParams`>> table attribute as follows:

[source, html]
----
<table id="myTableId" dt:table="true" dt:url="@{/ajax/persons-via-post}" dt:serverside="true" dt:ajaxParams="app-ajax#customAjaxParams">
  ...
</table>
----

=== 8.3. Customizing column contents

Since the v0.8.7, you can add customized column content using AJAX sources. It can be very useful for instance to display an "actions" column or if you need to display a bit more than just the raw data (e.g. a mailto link).

Using DOM sources, you can use the <<jsp-table-row, `row`>> table attribute but using AJAX source, the table's build if fully delegated to DataTables. So the only way to customize the column content is to do it client-side, passing a particular Javascript function.
   
So, you have to:

* Step 1: write a Javascript function that will be internally used by DataTables

+
[source, javascript]
----
function yourFunction(data, type, full) {
  return '<a href="' + data + '">Download</a>';
}
----

+
The Javascript function takes 3 parameters :

** {array|object} The data source for the row (based on mData)</li>
** {string} The type call data requested - this will be 'filter', 'display', 'type' or 'sort'.</li>
** {array|object} The full data source for the row (not based on mData)</li>

+
TIP: You can use the first parameter (data) of the function if you already use the <<jsp-column-property, `property`>> (JSP) or <<tml-th-property, `dt:property`>> (Thymeleaf) attribute because it internally generates a http://datatables.net/reference/option/data[data] parameter that you can reuse.

* Step 2: tell Dandelion-Datatables you want to use a custom rendering function for a particular column using either the <<jsp-column-renderFunction, `renderFunction`>> column attribute (JSP) or the <<jsp-column-renderFunction, `dt:renderFunction`>> th attribute (Thymeleaf). 

WARNING: Note that you can't use the <<jsp-column-format, `format`>> column attribute of the JSP taglib when using an AJAX source!

==== 8.3.1. Example, using a mailify function

This example shows how to generate a `mailto` link inside a column.

First, ensure the following function is properly made available to the table:

[source, javascript]
----
function mailify(data, type, full) {
   return '<a href="mailto:' + data + '">' + data + '</a>';
}
----

[discrete]
===== Using JSP

Then, use the <<jsp-column-renderFunction, `renderFunction`>> column attribute and pass the name of the previous JavaScript function:

[source, xml]
----
<datatables:table id="myTableId" url="/persons" serverSide="true">
  ...
  <datatables:column title="Mail" property="mail" renderFunction="mailify" />
</datatables:table>
----

[discrete]
===== Using Thymeleaf

Use the <<tml-th-renderFunction, `dt:renderFunction`>> th attribute as follows:

[source, html]
----
<table id="myTableId" dt:table="true" dt:url="@{/ajax/persons}" dt:serverside="true">
  <thead>
    <tr>
      ...
      <th dt:property="mail" dt:renderFunction="mailify">Mail</th>
    </tr>
  </thead>
</table>
----

==== 8.3.2. Another example for an "Actions" column

You can use the same mechanism to add an extra "Actions" column. For example, let's add another column which will contain some links.

[discrete]
===== Using JSP

[source, xml]
----
<datatables:table id="myTableId" url="/persons" serverSide="true" processing="true">
  ...
  <datatables:column title="Actions" renderFunction="actions" />
</datatables:table>
----

Then you just need to generate HTML code in the function as follows:

[source, javascript]
----
function actions(data, type, full) {
   return '<a class="btn btn-mini" href="/delete/' + full.id + '">Delete data</a>'
        + '<a class="btn btn-mini" href="/edit/' + full.id + '">Edit data</a>';
}
----

TIP: This time, the "Actions" column doesn't use any property of the iterated bean. That's why you should use the third parameter (full) of the Javascript function, which holds the full data source for the row exposed as a JSON object.

[discrete]
===== Using Thymeleaf

Using Thymeleaf, you can use the <<tml-th-renderFunction, `dt:renderFunction`>> th attribute in the same manner.

[source, html]
----
<table id="myTableId" dt:table="true" dt:url="@{/persons}" dt:serverSide="true">
  <thead>
    <tr>
      ...
      <th dt:property="mail" dt:renderFunction="mailify">Mail</th>
    </tr>
  </thead>
</table>
----

==== 8.3.3. Handling null and default values

This section deals with the case where the bean you're iterating on contains some null properties.

[discrete]
===== Using JSP

Using JSP with AJAX sources, null values are handled in the same way than for DOM sources. By default, an empty string will be displayed.

You can also use the <<jsp-column-default, `default`>> column attribute to replace the empty string by anything you want.

[source, xml]
----
<datatables:table id="myTableId" url="/persons">
   <datatables:column title="Id" property="id" />
   <datatables:column title="FirstName" property="firstName" />
   <datatables:column title="LastName" property="lastName" />
   <datatables:column title="City" property="address.town.name" default="My default value !" />
   <datatables:column title="Mail" property="mail" />
</datatables:table>
----

[discrete]
===== Using Thymeleaf

Using Thymeleaf, this is quite similar. Just use the <<tml-th-default, `dt:default`>> th attribute to override the default empty string.

[source, html]
----
<table id="myTableId" dt:table="true" dt:url="@{/persons}">
  <thead>
    <tr>
      ...
      <th dt:property="address.town.name" dt:default="My default value !">City</th>
      ...
    </tr>
  </thead>
</table>
----

=== 8.4. Server-side processing

If you are working with seriously large databases, you might want to consider using the server-side options that DataTables provides and that Dandelion-Datatables supports.

==== 8.4.1. How does it work?

When using server-side processing, DataTables will make an XHR request to the server for each draw of the information on the page (i.e. when paging, sorting, filtering etc). DataTables will send a number of variables to the server to allow it to perform the required processing, and then return the data in the format required by DataTables.

Dandelion-Datatables can help you during this process by providing you some utility classes:

* `DatatablesCriterias`:

This class mainly contains a `getFromRequest(HttpServletRequest request)` method that maps all the DataTables parameters into itself, allowing you to use it in your data access layer.

* `DataSet`:

All results returned from your data access layer should be wrapped into this class in order to build a `DataTablesResponse`.

* `DatatablesResponse`:

This class contains a builder that helps you to return the data in the format required by DataTables. Ensure this object is converted to JSON before displaying the table.

TIP: Note that an integration with Spring has been developed. Read more in the <<8-6-integration-with-spring, integration with Spring section>>

==== 8.4.2. Preparing the ground...

As you may expect, server-side processing requires a bit more work than client-side one. Here are the needed steps to set this up.

All snippets below are extracted from both **datatables-jsp-ajax** and **datatables-thymeleaf-ajax** samples.

===== Prepare the needed SQL queries using your favorite ORM framework

Whether you use Hibernate or any other ORM framework, you need to write some methods, knowing that you can use an instance of `DatatablesCriterias` to help building the queries.

.com.github.dandelion.datatables.repository.jpa.PersonJpaRepository
[source, java]
----
@Repository
public class PersonJpaRepository implements PersonRepository {

  @PersistenceContext
  private EntityManager entityManager;

  public List<Person> findAll() {
    TypedQuery<Person> query = entityManager.createQuery("SELECT p FROM Person p", Person.class);
    return query.getResultList();
  }

  public List<Person> findLimited(int maxResult) {
    TypedQuery<Person> query = entityManager.createQuery("SELECT p FROM Person p", Person.class);
    query.setMaxResults(maxResult);
    return query.getResultList();
  }

  public List<Person> findPersonWithDatatablesCriterias(DatatablesCriterias criterias) {

    StringBuilder queryBuilder = new StringBuilder("SELECT p FROM Person p");

    /**
     * Step 1: global and individual column filtering
     */
    queryBuilder.append(PersonRepositoryUtils.getFilterQuery(criterias));

    /**
     * Step 2: sorting
     */
    if (criterias.hasOneSortedColumn()) {

      List<String> orderParams = new ArrayList<String>();
      queryBuilder.append(" ORDER BY ");
      for (ColumnDef columnDef : criterias.getSortingColumnDefs()) {
        orderParams.add("p." + columnDef.getName() + " " + columnDef.getSortDirection());
      }

      Iterator<String> itr2 = orderParams.iterator();
      while (itr2.hasNext()) {
        queryBuilder.append(itr2.next());
        if (itr2.hasNext()) {
          queryBuilder.append(" , ");
        }
      }
    }

    TypedQuery<Person> query = entityManager.createQuery(queryBuilder.toString(), Person.class);

    /**
     * Step 3: paging
     */
    query.setFirstResult(criterias.getStart());
    query.setMaxResults(criterias.getLength());

    return query.getResultList();
  }

  public Long getFilteredCount(DatatablesCriterias criterias) {

    StringBuilder queryBuilder = new StringBuilder("SELECT p FROM Person p");

    queryBuilder.append(PersonRepositoryUtils.getFilterQuery(criterias));

    Query query = entityManager.createQuery(queryBuilder.toString());
    return Long.parseLong(String.valueOf(query.getResultList().size()));
  }

  public Long getTotalCount() {
    Query query = entityManager.createQuery("SELECT COUNT(p) FROM Person p");
    return (Long) query.getSingleResult();
  }
}
----

===== Create (or adapt) a business service

Create or adapt a business service with a method that returns a `DataSet` object.

.com.github.dandelion.datatables.service.PersonServiceImpl
[source, java]
----
public DataSet<Person> findPersonsWithDatatablesCriterias(DatatablesCriterias criterias) {

  List<Person> persons = personRepository.findPersonWithDatatablesCriterias(criterias);
  Long count = personRepository.getTotalCount();
  Long countFiltered = personRepository.getFilteredCount(criterias);
  
  return new DataSet<Person>(persons, count, countFiltered);
}
----

===== Write a JSON web service

Create a web service that will be used by DataTables to perform the AJAX request. Note that it must produce JSON only.

.com.github.dandelion.datatables.web.ajax.AjaxController
[source, java]
----
@RequestMapping(value = "/persons")
public @ResponseBody DatatablesResponse<Person> findAllForDataTables(HttpServletRequest request) {
  DatatablesCriterias criterias = DatatablesCriterias.getFromRequest(request);
  DataSet<Person> persons = personService.findPersonsWithDatatablesCriterias(criterias);
  
  return DatatablesResponse.build(persons, criterias);
}
----

===== Update views

You need to update your views in order to activate server-side processing. See the section below.

==== 8.4.3. Activating server-side processing

[discrete]
===== Using JSP

Use the <<jsp-table-serverSide, `serverSide`>> table attribute as follows.

[source, xml]
----
<datatables:table id="myTableId" url="/persons" serverSide="true">
  ...
</datatables:table>
----

[discrete]
===== Using Thymeleaf

Use the <<tml-table-serverSide, `dt:serverside`>> table attribute as follows:

[source, html]
----
<table id="myTableId" dt:table="true" dt:url="@{/persons}" dt:serverside="true">
  ...
</table>
----

==== 8.4.4. Pipelining data

When using server-side processing with DataTables, it can be quite intensive on your server having an Ajax call every time the user performs some kind of interaction - you can effectively DDOS your server with your own application!

You might over-come this by modifying the request set to the server to retrieve more information than is actually required for a single page's display. This means that the user can page multiple times (5 times the display size is the default) before a request must be made of the server. Paging is typically the most common interaction performed with a DataTable, so this can be most beneficial to your server's resource usage. Of course the pipeline must be cleared for interactions other than paging (sorting, filtering etc), but that's the trade off that can be made (sending extra information is cheap - while another XHR is expensive).

[discrete]
===== Using JSP

Use the <<jsp-table-pipelining, `pipelining`>> table attribute as follows:

[source, xml]
----
<datatables:table id="myTableId" url="/persons" serverSide="true" pipelining="true" pipeSize="6">
  ...
</datatables:table>
----

[discrete]
===== Using Thymeleaf

Use the <<tml-table-pipelining, `dt:pipelining`>> table attribute as follows:

[source, html]
----
<table id="myTableId" dt:table="true" dt:url="@{/persons}" dt:serverside="true" dt:pipelining="true" dt:pipesize="6">
  ...
</table>
----

TIP: Note that you can also set the pipe size using the <<jsp-table-pipeSize, `pipeSize`>> / <<tml-table-pipeSize, `dt:pipesize`>> table attributes (which defaults to 5).

==== 8.4.5. Deferring data loading

When using server-side processing, the default mode of operation for DataTables is to simply throw away any data that currently exists in the table and make a request to the server to get the first page of data to display. This is fine for an empty table, but if you already have the first page of data displayed in the plain HTML, it is a waste of resources. As such, this feature allows you to instruct DataTables to not make that initial request, rather it will use the data already on the page (no sorting etc will be applied to it).

The <<jsp-table-deferLoading, `deferLoading`>> (JSP) / <<tml-table-deferLoading, `dt:deferLoading`>> (Thymeleaf) attribute is used to indicate that deferred loading is required, but it is also used to tell DataTables how many records there are in the full table (allowing the information element and pagination to be displayed correctly). In the case where a filtering is applied to the table on initial load, this can be indicated by giving the parameter as an array, where the first element is the number of records available after filtering and the second element is the number of records without filtering (allowing the table information element to be shown correctly).

[discrete]
===== Using JSP

Use the <<jsp-table-deferLoading, `deferLoading`>> table attribute as follows:

[source, xml]
----
<datatables:table id="myTableId" url="/persons" serverSide="true" deferLoading="10">
  ...
</datatables:table>
----

[discrete]
===== Using Thymeleaf

Use the <<tml-table-deferLoading, `dt:deferLoading`>> table attribute as follows:

[source, html]
----
<table id="myTableId" dt:table="true" dt:url="@{/persons}" dt:serverside="true" dt:deferLoading="10">
  ...
</table>
----

=== 8.5. Reloading data

By default, the configured URL is used at initialisation time only. However it can be useful to re-read an AJAX source and have the table update.

Starting from the v0.10.0, Dandelion-Datatables provides utilities to allow data reloading.

==== 8.5.1. Default reloading

The default reloading fits for use cases when you just need a "Refresh" button/link. Internally, Dandelion-Datatables will load the needed API and call the http://www.datatables.net/plug-ins/api/fnReloadAjax[`fnReloadAjax`] function.

Dandelion-Datatables makes available the <<jsp-table-reloadSelector, `reloadSelector`>> (JSP) / <<tml-table-reloadSelector, `dt:reloadSelector`>> (Thymeleaf) attribute. You just need to pass in a jQuery selector targeting the element on which a 'click' event will be bound to trigger the table reloading.

[discrete]
===== Using JSP

[source, xml]
----
<a id="reload">Click me to refresh the table!</a>

<datatables:table id="myTableId" url="/persons" serverSide="true" reloadSelector="#reload">
  <datatables:column title="Id" property="id" />
  <datatables:column title="FirstName" property="firstName" />
  <datatables:column title="LastName" property="lastName" />
  <datatables:column title="City" property="address.town.name" />
  <datatables:column title="Mail" property="mail" />
</datatables:table>
----

[discrete]
===== Using Thymeleaf

[source, html]
----
<a id="reload">Click me to refresh the table!</a>   

<table id="myTableId" dt:table="true" dt:url="@{/ajax/persons}" dt:serverside="true" dt:reloadSelector="#reload">
  <thead>
    <tr>
      <th dt:property="id">Id</th>
      <th dt:property="firstName">Firstname</th>
      <th dt:property="lastName">Lastname</th>
      <th dt:property="address.town.name">City</th>
      <th dt:property="mail">Mail</th>
    </tr>
  </thead>
</table>
----

==== 8.5.1. Custom reloading

If you need to configure more actions during a data reloading, you may prefer to use the custom reloading.

You can use the <<jsp-table-reloadFunction, `reloadFunction`>> (JSP) / <<tml-table-reloadFunction, `dt:reloadFunction`>> (Thymeleaf) table attribute. Just pass the name of a JavaScript function that will be called in the 'click' event bound by the <<jsp-table-reloadSelector, `reloadSelector`>> (JSP) / <<tml-table-reloadSelector, `dt:reloadSelector`>> (Thymeleaf) attribute.

Note that when using this attribute, you will have to call manually the http://www.datatables.net/plug-ins/api/fnReloadAjax[`fnReloadAjax`] function.</p>

Assuming the following custom function:

[source, javascript]
----
function customReload() {
  // Some custom code...
 
  oTable_myTableId.fnReloadAjax();
 
  // Some custom code...
}
----

In the example below, a click on the link with ID "reload" will call the `customReload()` function.

[discrete]
===== Using JSP

[source, html]
----
<a id="reload">Click me to refresh the table!</a>

<datatables:table id="myTableId" url="/persons" serverSide="true" reloadSelector="#reload" reloadFunction="customReload">
  <datatables:column title="Id" property="id" />
  <datatables:column title="FirstName" property="firstName" />
  <datatables:column title="LastName" property="lastName" />
  <datatables:column title="City" property="address.town.name" />
  <datatables:column title="Mail" property="mail" />
</datatables:table>
----

[discrete]
===== Using Thymeleaf

[source, html]
----
<a id="reload">Click me to refresh the table!</a>   

<table id="myTableId" dt:table="true" dt:url="@{/ajax/persons}" dt:serverside="true" dt:reloadSelector="#reload" dt:reloadFunction="customReload">
  <thead>
    <tr>
      <th dt:property="id">Id</th>
      <th dt:property="firstName">Firstname</th>
      <th dt:property="lastName">Lastname</th>
      <th dt:property="address.town.name">City</th>
      <th dt:property="mail">Mail</th>
    </tr>
  </thead>
</table>
----

=== 8.6. Integration with Spring

Wether you use client-side or server-side processing, the Spring extra provides some utility classes to work with AJAX sources.

==== 8.6.1. Installing the Spring extra

.Example with Apache Maven
[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>com.github.dandelion</groupId>
  <artifactId>datatables-spring3</artifactId>
  <version>{project-version}</version>
</dependency>
----

==== 8.6.2. Custom method argument resolver for `DatatablesCriterias`

This custom resolver can be used to map the DataTables' attributes obtained from the `HttpServletRequest` to a `DatatablesCriterias` object  annotated with `@DatatablesParam`.

===== Before Spring 3.1

You can use the `com.github.dandelion.datatables.extras.spring3.ajax.DatatablesCriteriasResolver` by carrying out the following steps:

. Register the custom `WebArgumentResolver` with the following XML configuration:

+
[source, xml]
----
<mvc:annotation-driven>
   <mvc:argument-resolvers>
      <bean class="com.github.dandelion.datatables.extras.spring3.ajax.DatatablesCriteriasResolver" />
   </mvc:argument-resolvers>
</mvc:annotation-driven>
----

. You can then use it in any Spring controller like this:

+
[source, xml]
----
@RequestMapping(value = "/persons")
public @ResponseBody DatatablesResponse<Person> findAll(@DatatablesParams DatatablesCriterias criterias) {
   DataSet<Person> dataSet = personService.findPersonsWithDatatablesCriterias(criterias);
   return DatatablesResponse.build(dataSet, criterias);
}
----

===== Starting from Spring 3.1

You can use a the `com.github.dandelion.datatables.extras.spring3.ajax.DatatablesCriteriasMethodArgumentResolver` by carrying out the following steps:

. Register the custom method argument resolver, either using XML configuration...

+
[source, xml]
----
<mvc:annotation-driven>
   <mvc:argument-resolvers>
      <bean class="com.github.dandelion.datatables.extras.spring3.ajax.DatatablesCriteriasMethodArgumentResolver" />
   </mvc:argument-resolvers>
</mvc:annotation-driven>
----

+
Or using JavaConfig:

+
[source, java]
----
@Configuration
@EnableWebMvc
public class MyWebConfig extends WebMvcConfigurerAdapter {
  @Override
  public void addArgumentResolvers(List<HandlerMethodArgumentResolver> argumentResolvers) {
    argumentResolvers.add(new DatatablesCriteriasMethodArgumentResolver());
  }
}
----

. You can then use it in any Spring controller like this:

+
[source, java]
----
@RequestMapping(value = "/persons")
public @ResponseBody DatatablesResponse<Person> findAll(@DatatablesParams DatatablesCriterias criterias) {
  DataSet<Person> dataSet = personService.findPersonsWithDatatablesCriterias(criterias);
  return DatatablesResponse.build(dataSet, criterias);
}
----
