== 4. Basic features

=== 4.1. Data sources

DataTables can obtain data from four different fundamental sources. Listed below are all data sources currently supported by Dandelion-Datatables.

.Supported data sources
|===
|Data source type |Supported by Dandelion-Datatables |More information

|HTML document (DOM)
|icon:check[]
|See the <<jsp-table-data, `data`>> table attribute of the <<a-1-code-datatables-table-code-tag, `<datatables:table>`>> tag 

|JavaScript (array / objects)
|icon:check-empty[]
|See https://github.com/dandelion/dandelion-datatables/issues/265[#265]

|AJAX sourced data with client-side processing
|icon:check[]
|See the <<jsp-table-url, `url`>> table attribute of the <<a-1-code-datatables-table-code-tag, `<datatables:table>`>> tag and the <<8-1-using-ajax-sources, AJAX sources>> section

|AJAX sourced data with server-side processing
|icon:check[]
|See the <<jsp-table-url, `url`>> table attribute of the <<a-1-code-datatables-table-code-tag, `<datatables:table>`>> tag and the <<8-4-server-side-processing, server-side processing>> section
|===

=== 4.2. Feature enablement

Basic features such as sorting, paging, or filtering can be easily enabled/disabled using the corresponding table attributes.

You can see below all the features you can enable/disable by setting its value to `true`/`false`.
	
|===
|Features |JSP attributes |Thymeleaf attributes

|Sorting
|<<jsp-table-sortable,`sortable`>>
|<<tml-table-sortable,`dt:sortable`>>

|Filtering (Global top right input field)
|<<jsp-table-filterable,`filterable`>>
|<<tml-table-filterable,`dt:filterable`>>

|Paging
|<<jsp-table-pageable,`pageable`>>
|<<tml-table-pageable,`dt:pageable`>>

|Info ("Showing 1 to 10 of 200 entries")
|<<jsp-table-info,`info`>>
|<<tml-table-info,`dt:info`>>

|Length change (top left drop down list)
|<<jsp-table-lengthChange,`lengthChange`>>
|<<jsp-table-lengthChange,`dt:lengthChange`>>
|===

NOTE: Note that all above features are enabled by default.

[discrete]
==== Using JSP

For instance, using JSP, you can set the <<jsp-table-sortable,`sortable`>> table attribute to `false` to disable sorting.

[source,xml]
----
<datatables:table id="myTableId" data="${persons}" sortable="false">
  ...
</datatables:table>
----

[discrete]
==== Using Thymeleaf

Using Thymeleaf, set the <<tml-table-sortable,`dt:sortable`>> table attribute to `false`.

[source, html]
----
<table id="myTable" dt:table="true" dt:sortable="false">
  ...
</table>
----

=== 4.3. DOM positioning

When customising DataTables for your own usage, you might find that the default position of the feature elements (filter input etc) is not quite to your liking. Dandelion-Datatables leverages the DOM positioning feature of DataTables which is used to indicate where you wish particular features to appear in the DOM. You can also specify div wrapping containers (with classes) to provide complete layout flexibility.

The syntax available is:

* l - Length changing
* f - Filtering input
* t - The table!
* i - Information
* p - Pagination
* r - pRocessing
* < and > - div elements
* <"class" and > - div with a class

Since the v0.10.0, you can make use of this feature to configure your own control. See the <<7-2-using-extra-html-snippets, extra HTML section>> for more details.

[discrete]
==== Using JSP

You can use the <<jsp-table-dom,`dom`>> table attribute.

In the following example, all controls are disabled. Only the table is displayed.

[source,xml]
----
<datatables:table id="myTableId" data="${persons}" dom="t">
  ...
</datatables:table>
----

[discrete]
==== Using Thymeleaf

Use the <<tml-table-dom, `dt:dom`>> table attribute as follows:

[source,xml]
----
<table id="myTableId" dt:table="true" dt:dom="t">
  ...
</table>
----

Note that with the available parsers, you won't be able to directly use more complex expressions such as `<"class"t>` because some characters like `<` are not allowed.

If you do need expression like the above, use the properties trick as follows:

1. In your properties file associated with your template, add a new property for the `dom` value:

+
[source, xml]
----
myTableId.dom=<"myCSSClass"t>
----

2. Then use the created property in your template (http://www.thymeleaf.org/doc/usingthymeleaf.html#using-thtext-and-externalizing-text[more info here]):

+
[source, xml]
----
<table id="myTableId" dt:table="true" dt:dom="#{myTableId.dom}">
   ...
</table>
----

=== 4.4. Changing display length

By default, DataTables display 10 rows. You can of course configure this number.

[discrete]
=== Using JSP

You can use the <<jsp-table-displayLength, `displayLength`>> table attribute.

[source, xml]
----
<datatables:table id="myTableId" data="${persons}" displayLength="40">
  ...
</datatables:table>
----

[discrete]
=== Using Thymeleaf

With Thymeleaf, you can use the <<tml-table-displayLength, `dt:displayLength`>> table attribute.

[source, xml]
----
<table id="myTableId" dt:table="true" dt:displaylength="40">
  ...
</table>
----

=== 4.5. Using implicit objects

Dandelion-Datatables make some implicit objects available in the scope of the page.

==== 4.5.1. Accessing the object being iterated on

It can be handy if you need to display a bit more than just a raw property.

[discrete]
==== Using JSP

You will be able to access the object being iterated on thanks to the <<jsp-table-row,`row`>> table attribute. Just give a name under which you will refer the object in column bodies.

[source, xml]
----
<datatables:table id="myTableId" data="${persons}" row="person"> <1>
  <datatables:column title="Mail">
    <a href="mailto:${person.mail}">${person.mail}</a> <2>
  </datatables:column>
</datatables:table>
----
<1> A variable named `person` is created and contains the object being iterated on
<2> You can then access the object inside a column body

[discrete]
==== Using Thymeleaf

Actually, Dandelion-Datatables brings nothing here. Thymeleaf already allows you to access the object being iterated on thanks to the `th:each` attribute. See the http://www.thymeleaf.org/doc/usingthymeleaf.html#iteration[documentation] for more details.

[source, xml]
----
<table id="myTableId" dt:table="true">
  <thead>
    <tr>
      <th>Mail</th>
    </tr>
  </thead>
  <tbody>
    <tr th:each="person : ${persons}">
      <td><a th:href="${'mailto:' + person.mail}" th:text="${person.mail}">john@doe.com</a></td>
    </tr>
  </tbody>
</table>
----

==== 4.5.2. Accessing the current row index

[discrete]
==== Using JSP

Dandelion-Datatables makes available the row index through the <<jsp-table-row, `row`>> table attribute. The object accessed thanks to this attribute has a property called `_rowIndex`. Just use it as follows:

[source, xml]
----
<datatables:table id="myTableId" data="${persons}" row="person">
  <datatables:column title="Row index">
    Row index : <c:out value="${person_rowIndex}" />
  </datatables:column>
</datatables:table>
----

[discrete]
==== Using Thymeleaf

Once again, Dandelion-Datatables adds nothing here. http://www.thymeleaf.org[Thymeleaf] already offers a mechanism useful for keeping track of the status of the iteration. See http://www.thymeleaf.org/doc/usingthymeleaf.html#iteration[more details here].

[source, xml]
----
<table id="myTableId" dt:table="true">
  <thead>
    <tr>
      <th>Row index</th>
    </tr>
  </thead>
  <tbody>
    <tr th:each="person,iterStat : ${persons}">
      <td th:text="${iterStat.index}">0</td>
    </tr>
  </tbody>
</table>
----

==== 4.5.3. Accessing the DataTable configuration

The last objects available are Javascript ones: the DataTable object and the configuration to be used when initializing DataTable.

Indeed, whether you use the JSP taglib or the Thymeleaf dialect, Dandelion-Datatables generates the DataTable configuration using the table's id as follows:

[source, javascript]
----
var oTable_[tableId] = $('#[tableId]');
var oTable_[tableId]_params = {...};
$(document).ready(function(){
  oTable_[tableId] = $('#[tableId]').dataTable(oTable_[tableId]_params);
});
----

This means you can access the created DataTable object through the variable `oTable_[tableId]` but also the configuration to be applied to the table with the variable `oTable_[tableId]_params`.

See <<7-1-using-extra-javascript, extra JavaScript section>> for usage examples.

=== 4.6. Sorting data

==== 4.6.1. Individual column sorting

We have seen in <<4-2-feature-enablement, feature enablement section>> that global sorting can be enabled/disabled. But you can also enable/disable sorting on individual columns.

[discrete]
==== Using JSP

You can enable/disable the sorting feature in a specific column using the <<jsp-column-sortable, `sortable`>> column attribute:

[source, xml]
----
<datatables:table id="myTableId" data="${persons}">
  <datatables:column property="id" sortable="false" /> <1>
  <datatables:column property="firstName" />
  <datatables:column property="lastName" />
  <datatables:column property="address.town.name" />
  <datatables:column property="mail" sortable="false" /> <1>
</datatables:table>
----
<1> Sorting in the first and last columns is now impossible

[discrete]
==== Using Thymeleaf

You can enable/disable the sorting feature in a specific column using the <<tml-th-sortable, `dt:sortable`>> th attribute.

[source, xml]
----
<table id="myTableId" dt:table="true">
  <thead>
    <tr>
      <th dt:sortable="false">Id</th> <1>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>City</th>
      <th>Mail</th>
    </tr>
  </thead>
  <tbody>
    <tr th:each="person : ${persons}">
      <td th:text="${person.id}">1</td>
      <td th:text="${person.firstName}">John</td>
      <td th:text="${person.lastName}">Doe</td>
      <td th:text="${person.address.town.name}">Nobody knows!</td>
      <td th:text="${person.mail}">john@doe.com</td>
    </tr>
  </tbody>
</table>
----
<1> Sorting in the first column is now impossible

==== 4.6.2. Sorting initialization

Sorting can of course be initialized in many ways in individual columns.

===== 4.6.2.1. Default initialization order

[discrete]
===== Using JSP

Use the <<jsp-column-sortInitDirection, `sortInitDirection`>> column attribute, with either `asc` or `desc` as possible values, on each column you want sorting to be initialized.

[source, xml]
----
<datatables:table id="myTableId" data="${persons}">
  <datatables:column title="Id" property="id" sortable="false" />
  <datatables:column title="FirstName" property="firstName" sortInitDirection="desc" /> <1>
  <datatables:column title="LastName" property="lastName" />
  <datatables:column title="City" property="address.town.name" sortInitDirection="asc" /> <2>
 <datatables:column title="Mail" property="mail" sortable="false" />
</datatables:table>
----
<1> Sorting is first initialized in the second column
<2> Another sorting is then initialized in the fourth column

[discrete]
===== Using Thymeleaf

Use the <<tml-th-sortInitDirection, `sortInitDirection`>> th attribute with either `asc` or `desc` as possible values.

[source, xml]
----
<table id="myTableId" dt:table="true">
  <thead>
    <tr>
      <th >Id</th>
      <th dt:sortInitDirection="desc">Firstname</th>
      <th>Lastname</th>
      <th dt:sortInitDirection="asc">City</th>
      <th>Mail</th>
    </tr>
  </thead>
  ...
</table>
----

NOTE: Note that by default, columns are initialized in a sequential order, i.e. in the order columns are defined.

===== 4.6.2.2. Custom initialization order

As explained in the previous section, sorting is by default initialized in the order columns are defined. But you may need to change that.

[discrete]
===== Using JSP

The initialization order can be changed using the <<jsp-column-sortInitOrder, `sortInitOrder`>> column attribute. Just set the index in which you want the column to be initialized, starting from 0.

[source, xml]
----
<datatables:table id="myTableId" data="${persons}">
  <datatables:column title="Id" property="id" />
  <datatables:column title="FirstName" property="firstName" sortInitDirection="asc" sortInitOrder="1" /> <2>
  <datatables:column title="LastName" property="lastName" sortInitDirection="desc" sortInitOrder="0" /> <1>
  <datatables:column title="City" property="address.town.name" />
  <datatables:column title="Mail" property="mail" />
</datatables:table>
----
<1> The lastName column is first initialized in the `desc` direction
<2> Then the firstName column, in the `asc` direction

[discrete]
===== Using Thymeleaf

The initialization order can be changed using the <<tml-th-sortInitOrder, `dt:sortInitOrder`>> th attribute. Just set the index in which you want the column to be initialized, starting from 0.

[source, xml]
----
<table id="myTableId" dt:table="true">
  <thead>
    <tr>
      <th >Id</th>
      <th dt:sortInitDirection="asc" dt:sortInitOrder="1">Firstname</th>
      <th dt:sortInitDirection="desc" dt:sortInitOrder="0">Lastname</th>
      <th>City</th>
      <th>Mail</th>
    </tr>
  </thead>
  ...
</table>
----
 
==== 4.6.3. Sorting functions

Dandelion-Datatables uses a http://datatables.net/development/sorting#type_based[type based column sorting] among the http://datatables.net/development/sorting[available DataTables APIs]. It means the default sorting functions will be used in all columns unless you specify a specific sorting function name to be applied on a particular column.

===== 4.6.3.1. Available sorting functions

Since the v0.9.0, Dandelion-Datatables supports the following sorting functions:

.Built-in sorting functions
[cols="1,5,1,1"]
|===
|Sorting function |Description |JSP syntax |Thymeleaf syntax

|Alt string
|Use the `alt` attribute of an image tag as the data to sort upon
|<<jsp-column-sortType,`sortType`>>="alt_string"
|<<tml-column-sortType,`dt:sortType`>>="alt_string"

|Anti-"the"
|Sort with the prefixed word `dt-string The` removed, if present
|<<jsp-column-sortType,`sortType`>>="anti_the"
|<<tml-column-sortType,`dt:sortType`>>="anti_the"

|Chinese (String)
|Sort Chinese characters
|<<jsp-column-sortType,`sortType`>>="chinese_string"
|<<tml-column-sortType,`dt:sortType`>>="chinese_string"

|Date-de
|Sort date / time in the format `dd.mm.YYYY HH:mm` or `dd.mm.YYYY`
|<<jsp-column-sortType,`sortType`>>="date-de"
|<<tml-column-sortType,`dt:sortType`>>="date-de"

|Date-eu
|Sort dates in the format `dd/mm/YY[YY]` (with optional spaces)
|<<jsp-column-sortType,`sortType`>>="date-eu"
|<<tml-column-sortType,`dt:sortType`>>="date-eu"

|Date-euro
|Sort date / time in the format `dd/mm/YYY hh:ii:ss`
|<<jsp-column-sortType,`sortType`>>="date-euro"
|<<tml-column-sortType,`dt:sortType`>>="date-euro"

|Date-uk
|Sort dates in the format `dd/mm/YY`
|<<jsp-column-sortType,`sortType`>>="date-uk"
|<<tml-column-sortType,`dt:sortType`>>="date-uk"

|Filesize
|Sort abbreviated file sizes correctly (8MB, 4KB, etc)
|<<jsp-column-sortType,`sortType`>>="filesize"
|<<tml-column-sortType,`dt:sortType`>>="filesize"

|IP addresses
|Sort IP addresses numerically
|<<jsp-column-sortType,`sortType`>>="ip-address"
|<<tml-column-sortType,`dt:sortType`>>="ip-address" 

|Natural sorting
|DataTables implementation of the https://github.com/overset/javascript-natural-sort[naturalSort()] function by Jim Palmer. With this one, you can sort on
            simple numerics, floats, filenames, dates, currency, ...
            Long story short, this sorting function should cover the
            majority of your needs.
|<<jsp-column-sortType,`sortType`>>="natural"
|<<tml-column-sortType,`dt:sortType`>>="natural"

|Persian
|Sort Persian strings alphabetically
|<<jsp-column-sortType,`sortType`>>="persian"
|<<tml-column-sortType,`dt:sortType`>>="persian" 

|Scientific
|Sort data which is written in exponential notation
|<<jsp-column-sortType,`sortType`>>="scientific"
|<<tml-column-sortType,`dt:sortType`>>="scientific"

|Fully signed numbers
|Sort data numerically with a leading `+` symbol (as well as `-`).
|<<jsp-column-sortType,`sortType`>>="signed-num"
|<<tml-column-sortType,`dt:sortType`>>="signed-num"

|Turkish
|Sort Turkish characters
|<<jsp-column-sortType,`sortType`>>="turkish-string"
|<<tml-column-sortType,`dt:sortType`>>="turkish-string"
|===

[discrete]
===== Using JSP

You can activate a sorting function on a column using the <<jsp-column-sortType, `sortType`>> column attribute.

[source, xml]
----
<datatables:table id="myTableId" data="${persons}" row="person">
  <datatables:column title="Id" property="id" />
  <datatables:column title="FirstName" property="firstName" />
  <datatables:column title="LastName" property="lastName" />
  <datatables:column title="City" property="address.town.name" />
  <datatables:column title="Mail" sortType="natural">
    <a href="mailto:${person.mail}">${person.mail}</a>
  </datatables:column>
  <datatables:column title="Birthdate" property="birthDate" format="{0,date,dd/MM/yyyy}" sortType="date" />
  <datatables:column title="Pocket money" sortType="natural">
    ${person.pocketMoney}€
  </datatables:column>
  <datatables:column title="Company" property="company.name" />
</datatables:table>
----

[discrete]
===== Using Thymeleaf

You can activate a sorting function on a column using the <<tml-th-sortType, `dt:sortType`>> th attribute.

[source, xml]
<table id="myTableId" dt:table="true">
  <thead>
    <tr>
      <th>Id</th>
      <th>FirstName</th>
      <th>LastName</th>
      <th>City</th>
      <th dt:sortType="natural">Mail</th>
      <th dt:sortType="natural">Birthdate</th>
      <th dt:sortType="natural">Pocket money</th>
      <th>Company</th>
    </tr>
  </thead>
  <tbody>
    <tr th:each="person : ${persons}">
      <td th:text="${person.id}">1</td>
      <td th:text="${person.firstName}">John</td>
      <td th:text="${person.lastName}">Doe</td>
      <td th:text="${person.address.town.name}">Nobody knows!</td>
      <td th:text="${person.mail}">john@doe.com</td>
      <td th:text="${#dates.format(person.birthDate, 'dd/MM/yyyy')}">12/12/2012</td>
      <td th:text="${person.pocketMoney + '&euro;'}">1000€</td>
      <td th:text="${person.company.name}">Company</td>
    </tr>
  </tbody>
</table>
----

===== 4.6.3.2. Plugging-in your own sorting function

TIP: pending...

=== 4.7. Filtering data

In order to filter data, Dandelion-Datatables uses the great http://yadcf-showcase.appspot.com/[YADCF] plugin authored by https://github.com/vedmack[Daniel Reznick].
This plugin, which works on top of DataTables, will be automatically added as a new dependency as soon as a filtering feature is enabled.

==== 4.7.1. Using input fields

As soon as you activate individual column filtering, Dandelion-Datatables will generate the corresponding fields that allow to filter each column of the table.

By default, input fields will be generated in the corresponding `tfoot` cell.

[discrete]
===== Using JSP

Set the <<jsp-column-filterable, `filterable`>> column attribute to `true`.

[source, xml]
----
<datatables:table id="myTableId" data="${persons}">
   ...
   <datatables:column title="FirstName" property="firstName" filterable="true" />
   ...
</datatables:table>
----

[discrete]
===== Using Thymeleaf

With Thymeleaf, set the <<tml-th-filterable, `dt:filterable`>> th attribute to `true` to enable input-based filtering.

[source, xml]
----
<table id="myTableId" dt:table="true">
   <thead>
      <tr>
         ...
         <th dt:filterable="true">FirstName</th>
         ...
      </tr>
   </thead>
   ...
</table>
----

NOTE: Note that you can change the location of filtering elements. See <<4.7.3. Filtering placeholders, filtering placeholders section>> for more details.

==== 4.7.2. Using drop-down lists

Instead of the default input fields, you can choose to display drop-down lists.

===== 4.7.2.1. Using the default drop-down list

[discrete]
===== Using JSP

Set the <<jsp-column-filterType, `filterType`>> column attribute to `select` (which defaults to `input`).

[source, xml]
----
<datatables:table id="myTableId" data="${persons}">
   ...
   <datatables:column title="FirstName" property="firstName" filterable="true" filterType="select" />
   ...
</datatables:table>
----

[discrete]
===== Using Thymeleaf

With Thymeleaf, set the <<tml-th-filterType, `dt:filterType`>> th attribute to `select` (which defaults to `input`).

[source, xml]
----
<table id="myTableId" dt:table="true">
   <thead>
      <tr>
         ...
         <th dt:filterable="true" dt:filterType="select">FirstName</th>
         ...
      </tr>
   </thead>
   ...
</table>
----

By default, Dandelion-Datatables will generate a drop-down list and create as many options as entries in the corresponding column (minus duplicates).

WARNING: It is worth noting that the default drop-down lists (generated with the `select` filter type)
   are only compatible with DOM sources and AJAX sources (without
   server-side processing). For AJAX sources with server-side processing,
   this the section below.

===== 4.7.2.1. Using drop-down lists with predefined values

Instead of letting Dandelion-Datatables fill the filtering drop-down lists automatically, you may need to display predefined values.

For this purpose, you can use the <<jsp-column-filterValues, `filterValues`>> column attribute (JSP) / <<tml-th-filterValues, `dt:filterValues`>> th attribute (Thymeleaf) and pass any array of strings. Array of objects also works.

====== Example

Assuming the following asset bundled in the `filtering` bundle:

.dandelion/filtering.json
[source, json]
----
{  
  "assets":[  
    {  
      "locations":{  
        "webapp":"/assets/js/filtering.js"
      }
    }
  ]
}
----

The array can contain plain Strings or array of objects:

./assets/js/filtering.js
[source, javascript]
----
var arrayOfStrings = [ "1", "2" ];
// or
var arrayOfObjects = [{ "value" : "1", "label" : "One"} , { "value" : "2", "label" : "Two"}]; 
----

Finally, use the <<tml-th-filterValues, `dt:filterValues`>> th attribute as follows:

[source, xml]
----
<table id="myTableId" dt:table="true">
  <thead>
    <tr>
      <th>Id</th>
      <th>FirstName</th>
      <th>LastName</th>
      <th dt:filterable="true" dt:filterType="select" dt:filterValues="filtering#arrayOfObjects">City</th> <1>
      <th>Mail</th>
    </tr>
  </thead>
  ...
</table>
----
<1> Note that the `filtering` bundle is automatically included into the request thanks to the `bundle-name#javaScriptObject` syntax. See the <<14-3-bundle-special-syntax, bundle special syntax>> for more details.

NOTE: Note that these drop-down lists can be used with all types of data source: DOM, AJAX and AJAX + server-side processing.

==== 4.7.3. Filtering placeholders

You may have noticed that Dandelion-Datatables defaultly use the `tfoot` section of the table to place the filtering elements. Actually, you can choose where filtering elements will be inserted. Here follow the available placeholders:

.Available filtering placeholders
|===
|Placeholder |Description |JSP syntax |Thymeleaf syntax

|Footer
|All filtering elements will be inserted in the `tfoot` section of the table. Default value.
|<<jsp-table-filterPlaceholder, `filterPlaceholder`>> = "footer"
|<<tml-table-filterPlaceholder, `dt:filterPlaceholder`>> = "footer"

|Header
|All filtering elements will be inserted in the existing `thead` section.
|<<jsp-table-filterPlaceholder, `filterPlaceholder`>> = "header"
|<<tml-table-filterPlaceholder, `dt:filterPlaceholder`>> = "header"

|None
|The table is left untouched, no row is added. Use this option to let Dandelion-Datatables generate filtering elements in an <a href="using-an-external-form.html">external form</a>.
|<<jsp-table-filterPlaceholder, `filterPlaceholder`>> = "none"
|<<tml-table-filterPlaceholder, `dt:filterPlaceholder`>> = "none"
|===

==== 4.7.4. External form

At times, you might need to externalize all filtering elements out of the table. As shown above, you can the `none` filter placeholder.

===== 4.7.4.1. Using filtering selectors

You can tell Dandelion-Datatables to inject filtering elements (such as input fields or drop-down lists) in externalized placeholders.

First give all placeholders an `id`.

[source, xml]
----
<div id="firstNameFilter"></div>
<div id="lastNameFilter"></div>
<div id="cityFilter"></div>
----

Then, use the <<jsp-column-selector, `selector`>> column attribute (JSP) / <<tml-th-selector, `dt:selector`>> th attribute (Thymeleaf). As value, just pass the DOM id of the element in which you want the filter element to be inserted.

[discrete]
====== Using JSP

[source, xml]
----
<datatables:table id="myTableId" data="${persons}" filterPlaceholder="none">
  ...
  <datatables:column ... filterable="true" filterType="select" selector="firstNameFilter" />
  <datatables:column ... filterable="true" selector="lastNameFilter" />
  <datatables:column ... filterable="true" selector="cityFilter" />
  ...
</datatables:table>
----

====== Using Thymeleaf

[source, xml]
----
<table id="myTableId" dt:table="true" dt:filterPlaceholder="none">
  <thead>
    <tr>
      <th>Id</th>
      <th dt:filterable="true" dt:filterType="select" dt:selector="firstNameFilter">Firstname</th>
      <th dt:filterable="true" dt:selector="lastNameFilter">Lastname</th>
      <th dt:filterable="true" dt:selector="cityFilter">City</th>
      <th>Mail</th>
    </tr>
  </thead>
  ...
</table>
----

===== 4.7.4.2. Using the DataTables API

There is also an alternative way: use the http://datatables.net/api#fnFilter[`fnFilter`] method of the DataTables API.

Indeed, as soon as you use the JSP taglib or the Thymeleaf dialect, Dandelion-Datatables makes available a global-scoped variable containing the DataTables under the name `oTable_[tableId]`.

This means you can use the DataTables API with this variable.

====== Using JSP

Considering the following table:

[source, xml]
----
<datatables:table id="myTableId" data="${persons}">
  <datatables:column title="Id" property="id" />
  <datatables:column title="FirstName" property="firstName" />
  <datatables:column title="LastName" property="lastName" />
  <datatables:column title="City" property="address.town.name" />
  <datatables:column title="Mail" property="mail" />
</datatables:table>
----

You could add an external search form as follows:

[source, html]
----
<form ...>
  <input type="text" name="value1" />
  <a onclick="doSearch();">Search</a>
</form>

<script>
  function doSearch(){
    oTable_myTableId.fnFilter($('#value1').val()); // <1>
  }
</script>
----
<1> Note that the table is accessed with the following `oTable_myTableId` variable.

==== 4.7.5. Exclude columns from global filtering

There are times when you might find it useful to exclude some columns from filtering.

[discrete]
===== Using JSP

Use the <<jsp-column-searchable, `searchable`>> column attribute. Set it to `false` to exclude the corresponding column from filtering.

[source, xml]
----
<datatables:table id="myTableId" data="${persons}">
  ...
  <datatables:column title="FirstName" property="firstName" searchable="false" />
  ...
</datatables:table>
----

===== Using Thymeleaf

You can use the <<tml-th-searchable, `dt:searchable`>> th attribute. Set it to `false` to exclude the corresponding column from filtering.

[source, xml]
----
<table id="myTableId" dt:table="true">
  <thead>
    <tr>
      ...
      <th dt:searchable="false">Firstname</th>
      ...
    </tr>
  </thead>
  ...
</table>
----

==== 4.7.6. Filtering on click

Since the v0.10.0, data filtering can be done not only on key press but also on button click whether, you use a DOM or an AJAX source.

[discrete]
===== Using JSP

You can use the <<jsp-table-filterSelector, `filterSelector`>> table attribute, which needs a http://api.jquery.com/category/selectors/[jQuery selector].

[source, xml]
----
<datatables:table id="myTableId" data="${persons}" dom="l0rtip" filterSelector="#filterButton" filterClearSelector="#filterClearButton">
  <datatables:column ... filterable="true" filterType="select" />
  <datatables:column ... filterable="true" />
  <datatables:column ... filterable="true" />
  <datatables:extraHtml uid="0" cssStyle="float:right;">
    <a id="filterButton" class="btn btn-primary">Apply filters</a>
    <a id="filterClearButton" class="btn btn-inverse">Clear filters</a>
  </datatables:extraHtml>
</datatables:table>
----

At initialization, Dandelion-Datatables will automatically bind a _click_ event on the element targeted by the <<jsp-table-filterSelector, `filterSelector`>> attribute which will lead to a global filtering using all filled filtering elements.

To go a step further, note that you can do the same to clear the filters by assigning another http://api.jquery.com/category/selectors/[jQuery selector] to the element targeted by the <<jsp-table-filterClearSelector, `filterClearSelector`>> attribute. 

[discrete]
===== Using Thymeleaf

You can use the <<tml-table-filterSelector, `dt:filterSelector`>> table attribute to apply the filters and <<tml-table-filterClearSelector, `dt:filterClearSelector`>> to clear them.

[source, xml]
----
<div dt:conf="myTableId"> <1>
  <div dt:confType="extrahtml" dt:uid="0" dt:cssStyle="float:right;">
    <a id="filterButton">Apply filters</a>
    <a id="filterClearButton">Clear filters</a>
  </div>
</div>      

<table id="myTableId" dt:table="true" dt:dom="l0rtip" dt:filterSelector="#filterButton" dt:filterClearSelector="#filterClearButton">
  <thead>
    <tr>
      <th dt:name="firstname" dt:filterable="true" dt:filterType="select">Firstname</th>
      <th dt:name="lastname" dt:filterable="true">Lastname</th>
      <th dt:name="city" dt:filterable="true">City</th>
    </tr>
  </thead>
  ...
</table>
----
<1> See the <<7-6-configuration-div-thymeleaf-only, configuration div>> for more details.

==== 4.7.7. Delayed filtering

Starting from the v0.10.0, all individual filtering actions can be delayed (in ms) to keep the browser more responsive. This can be particularly useful when working with server-side processing, where you wouldn't typically want an AJAX request to be made with every key press the user makes when searching the table.

By default, the delay is set to 500ms.

[discrete]
====== Using JSP

Use the <<jsp-table-filterDelay, `filterDelay`>> table attribute to impact all filtering controls (except the global one).

[source, xml]
----
<datatables:table id="myTableId" url="/persons" serverSide="true" filterDelay="1000">
  ...
</datatables:table>
----

[discrete]
====== Using Thymeleaf

Use the <<tml-table-filterDelay, `dt:filterDelay`>> table attribute to impact all filtering controls (except the global one).

[source, xml]
----
<table id="myTableId" dt:table="true" dt:url="@{/persons}" dt:serverside="true" dt:filterDelay="1000">
  ...
</table>
----

WARNING: All filtering elements are impacted by the delay, except the global filtering control.

=== 4.8. Paging data

Dandelion-Datatables uses the extensible pagination mechanism of DataTables to offer different pagination style in an easy way.

Dandelion-Datatables supports the following pagination styles:

* simple
* simple_numbers 
* full
* full_numbers
* input
* listbox
* scrolling
* extStyle
* bootstrap_simple
* bootstrap_full
* bootstrap_full_numbers

[discrete]
===== Using JSP

Use the <<jsp-table-pagingType, `pagingType`>> table attribute.

[source, xml]
----
<datatables:table id="myTableId" ... pagingType="full_numbers">
  ...
</datatables:table>
----

[discrete]
===== Using Thymeleaf

Use the <<tml-table-pagingType, `dt:pagingType`>> table attribute.

[source, xml]
----
<table id="myTableId" dt:table="true" ... dt:pagingType="full_numbers">
  ...
</table>
----

=== 4.9. Scrolling

You may need to allow horizontal or vertical scrolling, e.g. when you have a wide table, with a large number of rows and/or columns to display.

==== 4.9.1. Vertical scrolling

[discrete]
===== Using JSP

Use the <<jsp-table-scrollY, `scrollY`>> table attribute.

[source, xml]
----
<datatables:table id="myTableId" ... scrollY="200px" pageable="false">
  ...
</datatables:table>
----

===== Using Thymeleaf

You can use the <<tml-table-scrolly, `dt:scrolly`>> table attribute.

[source, xml]
----
<table id="myTable" dt:table="true" ... dt:scrolly="200px" dt:pageable="false">
  ...
</table>
----

NOTE: Disabling table pagination is not mandatory, it will work just fine with pagination enabled as well

==== 4.9.2. Horizontal scrolling

[discrete]
===== Using JSP

You can use the <<jsp-table-scrollX, `scrollX`>> table attribute.

[source, xml]
----
<datatables:table id="myTableId" ... scrollX="120%">
  ...
</datatables:table>
----

[discrete]
===== Using Thymeleaf

[source, xml]
----
<table id="myTable" dt:table="true" ... dt:scrollx="120%">
  ...
</table>
----

=== 4.10. Multiple tables on the same page

Dandelion-Datatables can display multiple tables on the same page.

[source, xml]
----
<table id="myTableId" dt:table="true"> <1>
  <thead>
    <tr>
      <th>Id</th>
      <th>Firstname</th>
    </tr>
  </thead>
  <tbody>
    <tr th:each="person : ${persons}">
      <td th:text="${person?.id}">1</td>
      <td th:text="${person?.firstName}">John</td>
    </tr>
  </tbody>
</table>
 
<table id="myOtherTableId" dt:table="true"> <1>
  <thead>
    <tr>
      <th>Id</th>
      <th>Firstname</th>
    </tr>
  </thead>
  <tbody>
    <tr th:each="person : ${persons}">
      <td th:text="${person?.id}">1</td>
      <td th:text="${person?.firstName}">John</td>
    </tr>
  </tbody>
</table>
----
<1> Just ensure to give a unique ID to each table.

=== 4.11. Handling null and defaults values

There are times when you might want to display a property that is actually null. There are multiple ways to handle this.

[discrete]
==== Using JSP

By default, Dandelion-Datatables displays an empty string when the property of the bean is null. But you can override the empty string using the <<jsp-column-default, `default`>> column attribute.

[source, xml]
----
<datatables:table id="myTableId" data="${persons}">
  <datatables:column title="Id" property="id" />
  <datatables:column title="FirstName" property="firstName" />
  <datatables:column title="LastName" property="lastName" />
  <datatables:column title="City" property="address.town.name" default="Nothing to display!" />
  <datatables:column title="Mail" property="mail" />
</datatables:table>
----

Of course, you can also use some https://jstl.java.net/[JSTL] tags as follows:

[source, xml]
----
<datatables:table id="myTableId" data="${persons}">
  <datatables:column title="Id" property="id" />
  <datatables:column title="FirstName" property="firstName" />
  <datatables:column title="LastName" property="lastName" />
  <datatables:column title="City">
    <c:choose>
      <c:when test="${address ne null and address.town ne null and address.town.name ne ''}">
        <c:out value="${address.town.name}" />
      </c:when>
      <c:otherwise>Nothing to display!</c:otherwise>
    </c:choose>
  </datatables:column>
  <datatables:column title="Mail" property="mail" />
</datatables:table>
----

[discrete]
==== Using Thymeleaf

Dandelion-Datatables doesn't bring anything here. Just use a native conditionnal operator.

[source, xml]
----
<table id="myTableId" dt:table="true">
  <thead>
    <tr>
      <th>Id</th>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>City</th>
      <th>Mail</th>
    </tr>
  </thead>
  <tbody>
    <tr th:each="person : ${persons}">
      <td th:text="${person.id}">1</td>
      <td th:text="${person.firstName}">John</td>
      <td th:text="${person.lastName}">Doe</td>
      <td th:text="${person?.address != null and person.address.town != null} ? ${person.address.town.name} : 'Nothing to display!'">Nobody knows!</td>
         <td th:text="${person.mail}">john@doe.com</td>
      </tr>
   </tbody>
</table>
----

=== 4.12. Customizing column headers

At times it can be useful to have some HTML code in a column header, for example to display a _master checkbox_.

[discrete]
==== Using JSP

This can be done using the <<a-3-code-datatables-columnhead-code-tag, `<datatables:columnHead`>> tag, which works hand-in-hand with the <<a-2-code-datatables-column-code-tag, `<datatables:column>`>> tag.

As soon as you need to customize a column header, just wrap your custom code inside a <<a-3-code-datatables-columnhead-code-tag, `<datatables:columnHead`>> tag as follows: 

[source, xml]
----
<datatables:table id="myTableId" data="${persons}" row="person">
  <datatables:column title="Id" property="id" />
  <datatables:column title="FirstName" property="firstName" />
  <datatables:column title="LastName" property="lastName" />
  <datatables:column title="City" property="address.town.name" />
  <datatables:column title="Mail" property="mail" />
  <datatables:column sortable="false" cssCellStyle="text-align:center;">
    <datatables:columnHead> <1>
      <input type="checkbox" onclick="$('#myTableId').find(':checkbox').attr('checked', this.checked);" />
    </datatables:columnHead>
    <input type="checkbox" value="${person.id}" /> <2>
  </datatables:column>
</datatables:table>
----
<1> Anything inside the <<a-3-code-datatables-columnhead-code-tag, `<datatables:columnHead`>> tag will be displayed in the column header
<2> Anything else will be used for each cell's contents

==== Using Thymeleaf

Nothing's specific is needed with Thymeleaf since you have natively a full control over the `thead` section of the table.

[source, xml]
----
<table id="myTableId" dt:table="true">
  <thead>
    <tr>
      <th>Id</th>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>City</th>
      <th>Mail</th>
      <th dt:sortable="false">
        <input type="checkbox" onclick="$('#myTableId').find(':checkbox').attr('checked', this.checked);" />
      </th>
    </tr>
  </thead>
  <tbody>
    <tr th:each="person : ${persons}">
      <td th:text="${person.id}">1</td>
      <td th:text="${person.firstName}">John</td>
      <td th:text="${person.lastName}">Doe</td>
      <td th:text="${person.address.town.name}">Nobody knows !</td>
      <td th:text="${person.mail}">john@doe.com</td>
      <td style="text-align:center;">
        <input type="checkbox" th:value="${person.id}" />
      </td>
    </tr>
  </tbody>
</table>
----
