== 6. Export

Dandelion-Datatables provides two ways to handle table export:

* Either using a _servlet filter_: fast to set up but not very configurable and only compatible with DOM sources. Use it for basic exports only.
* Or using a _controller_ (such as Spring MVC `@Controller`s): this one offers you a full control over what is exported but requires a bit more work to set up. Compatible with DOM and AJAX sources.

Use one of the ways described above using the following compatibility matrix:

[cols="20,40l,40l"]
|===
||JSP |Thymeleaf

|**DOM Source** |Filter-based export
Controller-based export 
|Filter-based export
Controller-based export + <<tml-th-property,`dt:property`>>

|**AJAX source**
| Controller-based export
|Controller-based export + <<tml-th-property,`dt:property`>>
|===

=== 6.1. Introducing the export feature

Dandelion-Datatables provides ready-to-use features allowing to have an exportable table within seconds.

==== 6.1.1. How it works?

Whether you use _filter-based_ or _controller-based_ exports, Dandelion-Datatables uses an _export class_ that describes the layout of the exported file.

Dandelion-Datatables provides built-in exports classes for the following formats: **CSV**, **XML**, **PDF**, **XLS** and **XLSX**. These classes can be used to quickly set up export in your application.

Of course if you need to customize the rendered file, you can write your own export classes. It will be described in a later section. 

==== 6.1.2. Text-based export formats: CSV, XML

For the text-based export formats, such as CSV or XML, no additional dependency is required and built-in export classes (`CsvExport`, `XmlExport`) are bundled within the `datatables-core` artifact.

==== 6.1.3. Binary-based export formats: XLS, XLSX, PDF

Binary export formats, such as XLS or PDF, require most of the time some additional dependencies.

For these formats, Dandelion-Datatables provides some extras:

* PDF: `com.github.dandelion:datatables-export-itext:{project-version}`
* XLS: `com.github.dandelion:datatables-export-poi:{project-version}`
* XLSX: `com.github.dandelion:datatables-export-poi-ooxml:{project-version}` (Excel 2007 or later)

Each of those dependencies contains:

* an export class that will be used by default by Dandelion-Datatables if the corresponding export format is enabled in the table
* the corresponding third-party dependency (e.g. the iText library for the _datatatables-export-itext_ extra)

In order to use one of these extras, just add the corresponding dependency to your classpath.

For XLS export:

[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>com.github.dandelion</groupId>
  <artifactId>datatables-export-poi</artifactId>
  <version>{project-version}</version>
</dependency>
----

For XLSX export:

[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>com.github.dandelion</groupId>
  <artifactId>datatables-export-poi-ooxml</artifactId>
  <version>{project-version}</version>
</dependency>
----

For PDF export:

[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>com.github.dandelion</groupId>
  <artifactId>datatables-export-itext</artifactId>
  <version>{project-version}</version>
</dependency>
----

NOTE: These extras provide built-in export classes, with basic layouts. You can of course get inspired for writing your own. See below how to plug in your own export class.

=== 6.2. Filter-based exports

The export feature was initially designed to work with a servlet filter. The principle is simple: once you click on an export link, the configured filter intercepts the request, retrieves the table and renders it in the chosen format instead of displaying it in a view. 

This is the fastest way to make exports work. But in return, you won't be able to customize a lot the output file. For example, all data will be
   rendered, whether the table is paged or not. The same applies for filtering and sorting.

==== 6.2.1. Configure the servlet filter

Declare the servlet filter in your `web.xml` file as follows:

.web.xml
[source, xml]
----
<!-- Dandelion-Datatables filter, used for basic export -->
<filter>
  <filter-name>datatables</filter-name>
  <filter-class>com.github.dandelion.datatables.core.web.filter.DatatablesFilter</filter-class>
</filter>
<filter-mapping>
  <filter-name>datatables</filter-name>
  <url-pattern>/*</url-pattern>
</filter-mapping>
----

WARNING: Ensure to declare the Datatables servlet filter **after any other filter** that is used to encode your data, as the typical _org.springframework.web.filter.CharacterEncodingFilter_ 

Once the servlet filter configured, you have to <<6-4-activating-export, activate export locally>>.

==== 6.2.2. Customizing the export content

Even if filter-based exports provides less flexibility than controller-based ones, Dandelion-Datatables has some options allowing you to configure the export content just by using either the JSP taglib or the Thymeleaf dialect.

[discrete]
===== Using JSP

This is done thanks to the <<jsp-column-display, `display`>> column attribute. Just precise in this attribute in what format you want the corresponding content to appear. The format(s) you will precise must match with these set in the <<jsp-table-export, `export`>> attribute.

For instance, setting the <<jsp-column-display, `display`>> attribute to `html` means that the corresponding column will only appear in the HTML source code, not in the exported file.

In the following example, we don't want HTML code to be displayed in the exported Mail column. That's why a second Mail column is added with the <<jsp-column-display, `display`>> attribute set to `csv,xls` (i.e. not `html`) and with just the bean's property inside (thanks to the <<jsp-column-property, `property`>> attribute).

[source, xml]
----
<datatables:table id="myTableId" data="${persons}" row="person" export="xlsx">
  ...
  <datatables:column title="Mail" display="html"> <1>
    <a href="mailto:${person.mail}">${person.mail}</a>
  </datatables:column>
  <datatables:column title="Mail" property="mail" display="xlsx" /> <2>
  ...
</datatables:table>
----
<1> With `display="html"`, the corresponding column will appear in the HTML source code only
<2> With `display="xlsx"`, the "mail" property will appear in the XLSX export only

[discrete]
===== Using Thymeleaf

Using Thymeleaf, use one of the following td attribute to adapt the contents in the exported file: <<tml-td-csv, `dt:csv`>>, <<tml-td-xml, `dt:xml`>>, <<tml-td-pdf, `dt:pdf`>>, <<tml-td-xls, `dt:xls`>> or <<tml-td-xlsx, `dt:xlsx`>>.

[source, html]
----
<table id="myTableId" dt:table="true" dt:export="xlsx">
  <thead>
    <tr>
      <th>Mail</th>
    </tr>
  </thead>
  <tbody>
    <tr th:each="person : ${persons}">
      <td dt:xlsx="${person?.mail}"> <1>
        <a th:href="${'mailto:' + person?.mail}" th:text="${person?.mail}">john@doe.com</a> <2>
      </td>
    </tr>
  </tbody>
</table>
----
<1> With `dt:xlsx="${person?.mail}"`, the "mail" raw property will only appear in the XLSX export
<2> Standard `th` attributes are used to udpate the HTML source code

=== 6.3. Controller-based exports

Contrary to _filter-based exports_, _controller-based exports_ allow you to fully configure the content of the export. We could resume it to WYSIWYE: **W**hat **Y**ou **S**ee **I**s **W**hat **Y**ou **E**xport :-)

In return, you'll see in this section that it requires a bit more work.

==== 6.3.1. Setting up an export controller

Actually, there are several ways to do it:

* Writing a controller dedicated to all exports in your application
* Use only one controller that mixes methods that redirect to views and methods used for exporting data

Whichever method you use, note that you need to have two objects at your disposal: `HttpServletRequest` and `HttpServletResponse`.

===== Step 1/4: Retrieve table data

First step, you need to retrieve table data such as column definitions or information on sorting, paging, etc.

[source, java]
----
DatatablesCriterias criterias = DatatablesCriterias.getFromRequest(request); <1> <2>
----
<1> `request` is an instance of `HttpServletRequest`
<2> The `getFromRequest()` method will automatically map all table information into an instance of `DatatablesCriterias`

Once done, make use of the instance of `DatatablesCriterias` in your backend. For example:

[source, java]
----
List<Person> persons = personService.findPersonsWithDatatablesCriterias(criterias).getRows();
----

===== Step 2/4: Build an instance of `ExportConf`

Then, you need to build an instance of `ExportConf`, which allows you to configure the export in multiple ways:

* column headers displaying
* export file name
* auto size enablement (for Excel exports)
* export class: the Java class used to layout data in the exported file

A builder is available to ease its creation. See below an usage example with a CSV-based export:

[source, java]
----
ExportConf csvConf = new ExportConf.Builder(ReservedFormat.CSV) <1>
  .header(true) <2>
  .exportClass(new CsvExport()) <3>
  .build(); 
----
<1> You need to pass the desired export format in the constructor of the builder. Some formats use reserved keywords. See the `ReservedFormat` class
<2> the `header(true)` method indicates that column headers need to be displayed in the exported file
<3> the `exportClass(new CsvExport())` method is used to set up the class that will generate the contents of the exported file. Here we use the built-in `CsvExport` class

TIP: You can of course use your own export class. Read <<6-8-plugging-in-your-own-export-class, this section>> for more details.

===== Step 3/4: Build an instance of `HtmlTable`

Once you have both data and the associated export configuration, you can now build an instance of `HtmlTable`, which is the object used in any export class.

Once again, you have at your disposal a builder to ease its creation:

[source, java]
----
HtmlTable table = new HtmlTableBuilder<Person>().newBuilder("tableId", persons, request, csvConf) <1>
  .column().fillWithProperty("id").title("Id") <2> <3>
  .column().fillWithProperty("firstName").title("Firtname") <2>
  .column().fillWithProperty("lastName").title("Lastname") <2>
  .column().fillWithProperty("address.town.name").title("City") <2>
  .column().fillWithProperty("mail").title("Mail") <2>
  .column().fillWithProperty("birthDate", "{0,date,dd-MM-yyyy}").title("Birth date") <2>
  .build();
----
<1> Among other things, the builder needs the previously created instance of `ExportConf`
<2> Columns are easily added thanks to the `column()` method. A column is terminated with the `title()` method
<3> The contents of each column is configured using the `fillWith()`, `fillWithProperty()`, `and()` and `andProperty()` methods
   Note in the above example that:

===== Step 4/4: Render the exported file

Last step, you need to use the configured export class to generate the export content and write it to the response (instead of redirecting to a view).

Fortunately, a utility method has been written for that, located in the `ExportUtils` class. Use it as follows: 

[source, xml]
----
ExportUtils.renderExport(table, csvConf, response); <1> <2> <3>
----
<1> `table` is the instance of `HtmlTable`  built in the step 3
<2> `csvConf` is the instance of `ExportConf` built in the step 2
<3> `response` is the `HttpServletResponse` in which the contents of the export will be written (and proposed to download)

At this point, you have set up the plumbing necessary to make exports work. You can now <<6-4-activating-export, activate export locally>>.

==== 6.3.2. Example with Spring MVC

Here follows a complete example using Spring MVC.

[source, java]
----
@Controller
@RequestMapping(value = "/export") <1>
public class ExportController {
   
   @Autowired
   private PersonService personService;
   
   @RequestMapping(produces = "text/csv") <2>
   public void csv(@DatatablesParams DatatablesCriterias criterias, HttpServletRequest request, HttpServletResponse response) throws ExportException, IOException { <3>
	
   // Get data to export
   List<Person> persons = personService.findPersonsWithDatatablesCriterias(criterias).getRows();
   
   // Build the export configuration
   ExportConf csvConf = new ExportConf.Builder(ReservedFormat.CSV)
      .header(true)
      .exportClass(new CsvExport())
      .build();

   // Build the table to export from the data and the export configuration
   HtmlTable table = new HtmlTableBuilder<Person>().newBuilder("tableId", persons, request, csvConf)
      .column().fillWithProperty("id").title("Id")
      .column().fillWithProperty("firstName").title("Firtname")
      .column().fillWithProperty("lastName").title("Lastname")
      .column().fillWithProperty("address.town.name").title("City")
      .column().fillWithProperty("mail").title("Mail")
      .column().fillWithProperty("birthDate", "{0,date,dd-MM-yyyy}").title("BirthDate")
      .build();

   // Render the export in the browser
   ExportUtils.renderExport(table, exportCsvConf, response);
}
----
<1> All methods of this class are mapped to the `/export` request
<2> Here we just tell Spring that the method will produce CSV content. Since we use the default strategy of the content negociation manager (i.e. PPA, for path extension, then parameter, then Accept header), URLs like `http://domain/contextPath/export.csv` should match and the `csv(...)` method will be called
<3> The `@DatatablesParams` annotation is used here to automatically map the table information into a instance of `DatatablesCriterias`. Read the <<8-6-integration-with-other-projects, AJAX section>> for more details

=== 6.4. Activating export

[discrete]
===== Using JSP

Set the <<jsp-table-export, `export`>> table attribute to `csv` or whatever format you need. An export link will be generated (defaults to top right of the table).

You can of course set multiple formats, just separate them using a comma.

[source, xml]
----
<datatables:table id="myTableId" data="${persons}" export="csv,pdf">
  ...
</datatables:table>
----

[discrete]
===== Using Thymeleaf

Set the <<tml-table-export, `dt:export` >> to any export format you need.

[source, html]
----
<table id="myTableId" dt:table="true" dt:export="pdf,csv,xls,xml">
  ...
</table>  
----

NOTE: Note that by default, export links are ugly. Indeed, Dandelion-Datatables generates unstyled links by default in order to be as flexible as possible but you can of course adapt these links, as explained in the next section.

=== 6.5. Customizing export links

By defaut, export links are a bit ugly but you can of course customize them to fit your needs.

==== 6.5.1. Styling export links

[discrete]
===== Using JSP

Use the <<a-5-code-datatables-export-code-tag, `<datatables:export`>> 	tag to customize the export links. This tag allows you to configure one type of export at a time.

Using this tag, you can for instance add CSS classes to the links or change labels.

[source, xml]
----
<datatables:table id="myTableId" data="${persons}" export="csv,xml">
  ...
  <datatables:export type="csv" cssClass="btn" /> <1>
  <datatables:export type="xml" cssClass="btn" label="XML export" /> <2>
</datatables:table>
----
<1> This one will configure the CSV export
<2> This one will configure the XML export

[discrete]
===== Using Thymeleaf

All customizations are done thanks to the <<7-6-configuration-div-thymeleaf-only, configuration div>>. Use it as follows:

[source, xml]
----
<div dt:conf="myTableId"> <1>
  <div dt:confType="export" dt:type="pdf" dt:cssClass="btn" dt:url="@{/export.pdf}"></div> <2>
  <div dt:confType="export" dt:type="xls" dt:cssClass="btn" dt:url="@{/export.xls}"></div> <3>
</div>

<table id="myTableId" dt:table="true" dt:url="@{/persons}" dt:serverside="true" dt:processing="true" dt:export="pdf,xls"> <1>
  ...
</table>
----
<1> `dt:conf="myTableId"` and `id="myTableId"` must match
<2> Since the <<7-6-configuration-div-thymeleaf-only, configuration div>> is used to configure several feature, first you must specify that the customization only concerns the export feature, using `dt:confType="export"` and particularly the PDF one using `dt:type="pdf"`
<3> This one will configure the XLS export

==== 6.5.2. Adapt links position

By default, export links are displayed at top right. Depending on your needs, you may want to move links around the table.

Since the v0.10.0, export links generation is plugged in the <<4-3-dom-positioning, DOM positioning>> feature. A new letter has been made available: **E** (for **E**xport).

[discrete]
===== Using JSP

Use the <<jsp-table-dom, `dom`>> attribute as follows:

[source, xml]
----
<datatables:table id="myTableId" url="/persons" serverSide="true" processing="true" export="pdf,xls" dom="lEfrtiEp">
  ...
  <datatables:export type="pdf" cssClass="btn" url="/export.pdf" />
  <datatables:export type="xls" cssClass="btn" url="/export.xls" />
</datatables:table>
----

[discrete]
===== Using Thymeleaf

Use the <<tml-table-dom, `dt:dom`>> table attribute as follows:

[source, html]
----
<div dt:conf="myTableId">
  <div dt:confType="export" dt:type="pdf" dt:cssClass="btn" dt:url="@{/export.pdf}"></div>
  <div dt:confType="export" dt:type="xls" dt:cssClass="btn" dt:url="@{/export.xls}"></div>
</div>

<table id="myTableId" dt:table="true" dt:url="@{/persons}" dt:serverside="true" dt:processing="true" dt:export="pdf,xls" dt:dom="lEfrtiEp">
  ...
</table>
----

WARNING: For now, because of the limitation in the usage of the https://datatables.net/reference/option/dom[DOM DataTables' option], some conflicts may occur if multiple exportable tables are displayed on the same page

=== 6.6. Customizing export URLs

In cases where you want to use _controller-based exports_, you'll have to bypass the default export URLs generated by the library. It can easily be done using some attributes.

==== 6.6.1. Using a custom URL

You can choose to override the default export URL that is generated by the library. 

[discrete]
===== Using JSP

Use the <<jsp-export-url, `url`>> export attribute as follows:

[source, xml]
----
<datatables:table id="myTableId" url="/persons" serverSide="true" processing="true" export="csv">
  ...
  <datatables:export type="csv" cssClass="btn" url="/export.csv" />
</datatables:table>
----

[discrete]
===== Using Thymeleaf

As most of the customizations, you need to use the <<7-6-configuration-div-thymeleaf-only, configuration div>>, in particular the <<tml-div-url, `dt:url`>> attribute.

[source, html]
----
<div dt:conf="myTableId">
  <div dt:confType="export" dt:type="csv" dt:cssClass="btn" dt:url="@{/export.csv}"></div>
</div>

<table id="myTableId" dt:table="true" dt:url="@{/persons}" dt:serverside="true" dt:processing="true" dt:export="csv">
  ...
</table>
----

==== 6.6.2. Changing the HTTP method

By default, a HTTP GET is performed during the export call but you may wish to use another HTTP method.

[discrete]
===== Using JSP

Use the <<jsp-export-method, `method`>> export attribute as follows:

[source, xml]
----
<datatables:table id="myTableId" url="/persons" serverSide="true" processing="true" export="csv">
  ...
  <datatables:export type="csv" cssClass="btn" url="/export.csv" method="POST" />
</datatables:table>
----

[discrete]
===== Using Thymeleaf

Use the <<tml-div-method, `dt:method`>> attribute of the div marked with <code>confType="export"</code>.

[source, html]
----
<div dt:conf="myTableId"> <1>
  <div dt:confType="export" dt:type="csv" <2>
       dt:cssClass="btn" 
       dt:url="@{/export.csv}" 
       dt:label="Export using a HTTP POST" 
       dt:method="post"></div> <3>
</div>

<table id="myTableId" <1> 
       dt:table="true" dt:url="@{/persons}" dt:serverside="true" dt:processing="true" 
       dt:export="csv">
  ...
</table>
----
<1> Once again, ids must match
<2> The nested div must be specialized for export using `dt:confType="export"` and 
<3> The HTTP method is changed here

==== 6.7. Export options

Finally, some extra options are available in order to configure the export.

Using JSP, all options can be set via the <<a-5-code-datatables-export-code-tag, `<datatables:export>`>> tag.

Using Thymeleaf, you'll have to use the <<7-6-configuration-div-thymeleaf-only, configuration div>> introduced in the v0.10.0.

[cols="a,<,<"]
|===
|Option |Description |Compatible export formats

|**File name** |Name of the exported file (without extension) |CSV, XML, PDF, XLS, XLSX
3+|
.JSP Syntax
[source, xml]
----
<datatables:table id="tableId" ...>
  <datatables:export ... fileName="my-exported-file" />
</datatables:table>
----
3+|
.Thymeleaf syntax
[source, html]
----
<div dt:conf="tableId">
  <div dt:confType="export" dt:fileName="my-exported-file"></div>
</div>
----

|**File extension** |Extension of the exported file |CSV, XML, PDF, XLS, XLSX
3+|
.JSP Syntax
[source, xml]
----
<datatables:table id="tableId" ...>
  ...
  <datatables:export ... fileExtension="xls" />
</datatables:table>
----
3+|
.Thymeleaf syntax
[source, html]
----
<div dt:conf="tableId">
  <div dt:confType="export" dt:fileExtension="xls"></div>
</div>
----

|**Header inclusion** |Display/hide the header column in the exported file |CSV, PDF, XLS, XLSX
3+|
.JSP Syntax
[source, xml]
----
<datatables:table id="tableId" ...>
  ...
  <datatables:export ... includeHeader="true" />
</datatables:table>
----
3+|
.Thymeleaf syntax
[source, html]
----
<div dt:conf="tableId">
  <div dt:confType="export" dt:includeHeader="true"></div>
</div>
----

|**Orientation** |Orientation of the exported file |PDF
3+|
.JSP Syntax
[source, xml]
----
<datatables:table id="tableId" ...>
  ...
  <datatables:export ... orientation="landscape" />
</datatables:table>
----
3+|
.Thymeleaf syntax
[source, html]
----
<div dt:conf="tableId">
  <div dt:confType="export" dt:orientation="landscape" ></div>
</div>
----

|**Autosize** |Automatically adapts the cells size according to their contents |XLS, XLSX
3+|
.JSP Syntax
[source, xml]
----
<datatables:table id="tableId" ...>
  ...
  <datatables:export ... autoSize="true" />
</datatables:table>
----
3+|
.Thymeleaf syntax
[source, html]
----
<div dt:conf="tableId">
  <div dt:confType="export" dt:autoSize="true" ></div>
</div>
----
|===

=== 6.8. Plugging-in your own export class

Dandelion-Datatables is configured to use default export classes for each export format. Theses default classes are handy but provide basic layouts.

If you need some customizations, just write and activate your own export class as shown below.

==== 6.8.1. Writing your own export class

Begin by creating a class that implements the `DatatablesExport` interface.

[source, java]
----
package my.package;

public class MyExportClass implements DatatablesExport {

  private HtmlTable table;

  @Override
  public void initExport(HtmlTable table) {
    this.table = table;
    //  Some other stuff
  }

  @Override
  public void processExport(OutputStream output) throws ExportException {
    // Write anything inside the output using the HtmlTable instance
  }
}
----

Note that you can get inspired of all built-in export classes:

* Built-in XML export class: `XmlExport`
* Built-in CSV export class: `CsvExport`
* Built-in PDF export class: `PdfExport`
* Built-in XLS export class: `XlsExport`
* Built-in XLSX export class: `XlsxExport`

==== 6.8.2. Activating the custom export class

Once your export class created, you just need to register it inside the Dandelion-Datatables' configuration.

Depending on the export format, you'll have to use one of the following configuration property:

|===
|Export format |Corresponding option

|CSV |<<opt-export.csv.class, `export.csv.class`>>
|XML |<<opt-export.xml.class, `export.xml.class`>>
|PDF |<<opt-export.pdf.class, `export.pdf.class`>>
|XLS |<<opt-exportxls.class, `export.xls.class`>>
|XLSX |<<opt-export.xlsx.class, `export.xlsx.class`>>
|===

TIP: You have several alternatives to register your custom export class: globally, locally or using option groups. Read more in the <<11-configuration-options, configuration options>> section.
