== 9. I18n

=== 9.1. Introducing the i18n mechanism

Since the v0.9.0, Dandelion-Datatables has now full support for internationalization of column titles and surrounding information. Note that a support is also provided with <<9-2-integration-with-other-projects, other projects>>.

==== 9.1.1. Translating DataTables' information

All the i18n configuration takes place in the _dandelion/datatables/datatables.properties_ file. Lots of keys exist and allow you to configure the language information displayed by DataTables. You can see the <<opt-i18n.locale.resolver, full reference here>>.

In order to support other languages, you can add any number of additional files named _dandelion/datatables/datatables_LANGUAGE.properties_ in the same place as _dandelion/datatables/datatables.properties_. 

For example, if your application needs to support both English and French, you could have the following files:

* _dandelion/datatables/datatables.properties_: the main configuration file, containing non-translatable properties

+
[source, properties]
----
global.css.class=table table-striped table-bordered table-condensed
global.extra.theme=bootstrap2
----

* _dandelion/datatables/datatables_EN.properties_: the file containing all english translations 

+
[source, properties]
----
global.i18n.msg.processing=Processing...
global.i18n.msg.search=Search :
global.i18n.msg.info=Showing _START_ to _END_ of _TOTAL_ entries
----

* _dandelion/datatables/datatables_FR.properties_: the file containing all french translations

+
[source, properties]
----
global.i18n.msg.processing=Traitement en cours...
global.i18n.msg.search=Rechercher :
global.i18n.msg.info=Affichage de l'élément _START_ à _END_ sur _TOTAL_ éléments
---- 

Keep in mind you don't need to copy all the properties in all internationalized files because lots of them are also just "configuration properties" which don't need to be translated at all.

[TIP]
====
Note that:

* all properties can contain HTML tags
* `\_START_`, `\_END_` and `\_TOTAL_` variables are all dynamically replaced as the table display updates, and can be freely moved or removed as the language requirements change
====

==== 9.1.2. Translating column headers

It behaves in different ways depending on the template engine used in your application.

[discrete]
===== Using JSP

Dandelion-Datatables uses the following algorithm to define the content of a column header:

. The <<jsp-column-title, `title`>> column attribute has precedence over any other attribute. The content of this attribute will be always used in the column header, wether it's empty or not
. If the <<jsp-column-title, `title`>> column attribute is not used and if the <<jsp-column-titleKey, `titleKey`>> column attribute is used and not empty, the <<jsp-column-titleKey, `titleKey`>> attribute will be used to lookup a resource in the resource bundle. If the key cannot be found in the bundle, the **???key???** message will be used
. At this point, if no message is found, the <<jsp-column-property, `property`>> column attribute will be used (as text) and capitalized to fill in the column header
. Finally, in no <<jsp-column-property, `property`>> column attribute is used (which can happen when using the <<jsp-column-row, `row`>> table attribute), the column header will remain empty

Here is an usage example of the <<jsp-column-titleKey, `titleKey`>> column attribute:

[source, xml]
----
<datatables:table id="myTableId" data="${persons}">
  <datatables:column titleKey="table.header.id" property="id" />
  <datatables:column titleKey="table.header.firstname" property="firstName" />
  <datatables:column titleKey="table.header.lastname" property="lastName" />
  <datatables:column titleKey="table.header.city" property="address.town.name" />
  <datatables:column titleKey="table.header.mail" property="mail" />
</datatables:table>
----

[discrete]
===== Using Thymeleaf

You can use the `#{...}` syntax of the Thymeleaf standard dialect:

[source, html]
----
<table id="myTableId" dt:table="true">
  <thead>
    <tr>
      <th th:text="#{table.header.id}">Id</th>
      <th th:text="#{table.header.firstname}">Firstname</th>
      <th th:text="#{table.header.lastname}">Lastname</th>
      <th th:text="#{table.header.city}">City</th>
      <th th:text="#{table.header.mail}">Mail</th>
    </tr>
  </thead>
  ...
</table>
----

==== 9.1.3. Locale and message default resolution

By default, Dandelion-Datatables uses the `StandardLocaleResolver` to resolve the locale from the `HttpServletRequest`, i.e. from your browser. But if you need to override this behaviour, you can in two ways:

* by using one of the ready-to-use implementations of the `LocaleResolver` interface: see the <<9-2-integration-with-other-projects, integration with other projects>> for more details

* by plugging-in a custom implementation of the `LocaleResolver` interface: see the <<9-3-plugging-in-your-own-locale-resolver, plugging-in you own locale resolver section>> for more details

Regarding the message resolution, note that the `JstlMessageResolver` will be automatically enabled if the JSTL JAR is detected in the classpath and if no `i18n.message.resolver` option is used in your custom configuration file. This means that the <<jsp-column-titleKey, `titleKey`>> attributes will be evaluated in the same way as for the `<fmt:message>` JSTL tag. You can override this in two ways as well:

* by using one of the ready-to-use implementations of the `MessageResolver` interface: see the <<9-2-integration-with-other-projects, integration with other projects>> for more details

* by plugging-in your own implementation of the `MessageResolver` interface: see the <<9-4-plugging-in-your-own-message-resolver, plugging-in your own message resolver section>> for more details

=== 9.2. Integration with other projects

Dandelion will probably be used in an application where content is already internationalized using a specific framework, which should provide a way to resolve the current locale and to lookup properties in a resource bundle.

This section lists all ready-to-use adapters that allows you to use the same i18n support you are using in your application.

==== 9.2.1. Locale resolution

Listed below are the ready-to-use implementations of the `LocaleResolver` interface:

* for **Spring 3+** with the `SpringLocaleResolver` class

+
The resolver will use the `RequestContextUtils.getLocale()` method for locale resolution (which will in turn delegate to the Spring locale resolver)

+
To use it globally in your application, just add the following line in your <<11-1-configuration-loading, configuration file>>:

+
[source, properties]
----
i18n.locale.resolver=com.github.dandelion.datatables.extras.spring3.i18n.SpringLocaleResolver
----

+
The `SpringLocaleResolver` class lives in the **datatables-spring3** artifact, that should add to your classpath:

+
.Example with Apache Maven
[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>com.github.dandelion</groupId>
  <artifactId>datatables-spring3</artifactId>
  <version>{project-version}</version>
</dependency>
----

* for **JSTL** with the `JstlLocaleResolver` class

+
The resolver will first try to get the locale from the `Config.FMT_LOCALE` key first from the request and then from the session.

+
To use it globally in your application, just add the following line in your <<11-1-configuration-loading, configuration file>>:

+
[source, properties]
----
i18n.locale.resolver=com.github.dandelion.datatables.jsp.i18n.JstlLocaleResolver
----

+
[NOTE]
====
Note that if the JSTL is detected in the classpath and if no `i18n.message.resolver` option is used in your configuration file, the `JstlLocaleResolver` is auto-configured
====

* for **Struts 1** with the `Struts1LocaleResolver` class

+
The resolver will first try to get the locale from the `Globals.LOCALE_KEY` key and will fall back to request locale.

+
To use it globally in your application, just add the following line in your <<11-1-configuration-loading, configuration file>>:

+
[source, properties]
----
i18n.locale.resolver=com.github.dandelion.datatables.extras.struts1.i18n.Struts1LocaleResolver
----

+
The `Struts1LocaleResolver` class lives in the **datatables-struts1** artifact, that should add to your classpath:

+
.Example with Apache Maven
[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>com.github.dandelion</groupId>
  <artifactId>datatables-struts1</artifactId>
  <version>{project-version}</version>
</dependency>
----

* for **Struts 2** with the `Struts2LocaleResolver`class

+
The resolver will look for the first `LocaleProvider` action in the stack.

+
To use it globally in your application, just add the following line in your <<11-1-configuration-loading, configuration file>>:

+
[source, properties]
----
i18n.locale.resolver=com.github.dandelion.datatables.extras.struts2.i18n.Struts2LocaleResolver
----

+
The `Struts2LocaleResolver` class lives in the **datatables-struts2** artifact, that should add to your classpath:

+
.Example with Apache Maven
[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>com.github.dandelion</groupId>
  <artifactId>datatables-struts2</artifactId>
  <version>{project-version}</version>
</dependency>
----

==== 9.2.2. Message resolution

Other than resolving the currently used locale, your framework will probably provide a standard way to store i18n resources. Just like for the locale resolution, Dandelion-Datatables will allow you to plug in different implementations.

You will find below the existing ready-to-use implementations of the `MessageResolver` interface:

* for **Spring 3+** with the `SpringMessageResolver` class

+
The resolver will look for the message inside the configured `MessageSource` bean

+
To use it globally in your application, just add the following line in the <<11-1-configuration-loading, configuration file>>:

+
[source, properties]
----
global.i18n.message.resolver=com.github.dandelion.datatables.extras.spring3.i18n.SpringMessageResolver
----

+
The `SpringMessageResolver` class lives in the **datatables-spring3** artifact, that should add to your classpath:

+
.Example with Apache Maven
[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>com.github.dandelion</groupId>
  <artifactId>datatables-spring3</artifactId>
  <version>{project-version}</version>
</dependency>
----

* for **JSTL** with the `JstlMessageResolver`

+
The resolver will look for the message as the `<fmt:message>` does.

+
To use it globally in your application, just add the following line in your <<11-1-configuration-loading, configuration file>>:

+
[source, properties]
----
global.i18n.message.resolver=com.github.dandelion.datatables.jsp.i18n.JstlMessageResolver
----

+
[NOTE]
====
Note that if the JSTL is detected in the classpath, the `JstlMessageResolver` is auto-configured
====

* for **Struts1** with the `Struts1MessageResolver` class

+
The resolver will look for the message using the `Globals.MESSAGES_KEY`.

+
To use it globally in your application, just add the following line in your <<11-1-configuration-loading, configuration file>>:

+
[source, properties]
----
global.i18n.message.resolver=com.github.dandelion.datatables.extras.struts1.i18n.Struts1MessageResolver
----

+
The `Struts1MessageResolver` class lives in the **datatables-struts1** artifact, that should add to your classpath:

+
.Example with Apache Maven
[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>com.github.dandelion</groupId>
  <artifactId>datatables-struts1</artifactId>
  <version>{project-version}</version>
</dependency>
----

* for **Struts2** with the `Struts2MessageResolver` class

+
The resolver will look for the first `TextProvider` action in the stack.

+
To use it globally in your application, just add the following line in your <<11-1-configuration-loading, configuration file>>:

+
[source, properties]
----
global.i18n.message.resolver=com.github.dandelion.datatables.extras.struts2.i18n.Struts2MessageResolver
----

+
The `Struts2MessageResolver` class lives in the **datatables-struts2** artifact, that should add to your classpath:

+
.Example with Apache Maven
[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>com.github.dandelion</groupId>
  <artifactId>datatables-struts2</artifactId>
  <version>{project-version}</version>
</dependency>
----

WARNING: By default, no message resolver is configured

=== 9.3. Plugging-in your own locale resolver

Begin creating a class that implements the `LocaleResolver` interface.

All you have to do is to implement the `resolveLocale(HttpServletRequest request)` method.

[source, java]
----
package com.company.project;

public class MyLocaleResolver implements LocaleResolver {
   @Override
   public Locale resolveLocale(HttpServletRequest request) {
      // some stuff... 
   }
}
----

Then, to use it globally in your application, just add the following line to your <<11-1-configuration-loading, configuration file>>:

[source, properties]
----
i18n.locale.resolver.resolver=com.company.project.MyLocaleResolver
----

=== 9.4. Plugging-in your own message resolver

Create a class that implements the `MessageResolver` interface.

All you have to do is to implement the `getResource(String messageKey, String defaultValue, Object... params)` method.

[source, java]
----
package com.company.project;

public class MyMessageResolver extends AbstractMessageResolver {

   public MyMessageResolver(HttpServletRequest request) {
      super(request);
   }

   public String getResource(String messageKey, String defaultValue, Object... params) {
      // some stuff...
   }
}
----

Then, to use it globally in your application, just add the following line to your <<11-1-configuration-loading, configuration file>>:

[source, properties]
----
global.i18n.message.resolver=com.company.project.MyMessageResolver
----

NOTE: Note that contrary to `i18n.locale.resolver`, `i18n.message.resolver` can be grouped in an <<11-4-using-option-groups, option group>>
