== 10. Plugins

DataTables provides lots of awesome built-in http://datatables.net/extensions/index[plugins]. Dandelion-Datatables only support some of them but the scope will be extended in future versions.

=== 10.1. Scroller

Scroller is a virtual rendering plug-in for DataTables which allows large datasets to be drawn on screen every quickly. What the virtual rendering means is that only the visible portion of the table (and a bit to either side to make the scrolling smooth) is drawn, while the scrolling container gives the visual impression that the whole table is visible. This is done by making use of the pagination abilities of DataTables and moving the table around in the scrolling container DataTables adds to the page. The scrolling container is forced to the height it would be for the full table display using an extra element.

[discrete]
==== Using JSP

Enable the extension by adding `scroller` to the <<jsp-table-ext, `ext`>> table attribute.

By default, the height is `300px` but you can configure it with the <<jsp-table-scrollY, `scrollY`>> table attribute.

[source, xml]
----
<datatables:table id="myTableId" ... ext="scroller" scrollY="400px">
  ...
</datatables:table>
----

[discrete]
==== Using Thymeleaf

Enable the extension by adding `scroller` to the <<tml-table-ext, `dt:ext`>> table attribute. You can configure the height thanks to the <<tml-table-scrollY, `dt:scrollY`>> table attribute.

[source, html]
----
<table id="myTable" dt:table="true" dt:ext="scroller" dt:scrollY="400px">
  ...
</table>
----

=== 10.2. ColReorder

ColReorder adds the ability for the end user to click and drag column headers to reorder a table as they see fit, to DataTables. 

[discrete]
==== Using JSP

Enable the extension by adding `colreorder` to the <<jsp-table-ext, `ext`>> table attribute.

[source, xml]
----
<datatables:table id="myTableId" ... ext="colreorder">
  ...
</datatables:table>
----

[discrete]
==== Using Thymeleaf

Enable the extension by adding `scroller` to the <<tml-table-ext, `dt:ext`>> table attribute.

[source, html]
----
<table id="myTable" dt:table="true" ... dt:ext="colreorder">
  ...
</table>
----

=== 10.3. FixedHeader

At times it can be useful to ensure that column titles will remain always visible on a table, even when a user scrolls down a table. The FixedHeader plug-in for DataTables will float the 'thead' element above the table at all times to help address this issue. The column titles also remain click-able to perform sorting.

[discrete]
==== Using JSP

Enable the extension by adding `fixedheader` to the <<jsp-table-ext, `ext`>> table attribute.

[source, xml]
----
<datatables:table id="myTableId" ... fixedHeader="true">
  ...
</datatables:table>
----

[discrete]
==== Using Thymeleaf

Enable the extension by adding `fixedheader` to the <<tml-table-ext, `dt:ext`>> table attribute.

[source, xml]
----
<table id="myTable" dt:table="true" ... dt:ext="fixedheader">
  ...
</table>
----

=== 10.4. Responsive

In the modern world of responsive web design tables can often cause a particular problem for designers due to their row based layout. Responsive is an extension for DataTables that resolves that problem by optimising the table's layout for different screen sizes through the dynamic insertion and removal of columns from the table.

[discrete]
==== Using JSP

Enable the extension by adding `responsive` to the <<jsp-table-ext, `ext`>> table attribute.

[source, xml]
----
<datatables:table id="myTableId" ... ext="responsive">
  ...
</datatables:table>
----

[discrete]
==== Using Thymeleaf

Enable the extension by adding `responsive` to the <<tml-table-ext, `dt:ext`>> table attribute.

[source, xml]
----
<table id="myTable" dt:table="true" ... dt:ext="responsive">
  ...
</table>
----

Note that the plugin automatically adapts if a theme, such as Bootstrap2 or Bootstrap3, is being used.