== Appendix A: JSP taglib reference

=== A.1. `<datatables:table>` tag

The `<datatables:table>` tag allows you to display a HTML table thanks to a set of attributes and nested `<datatables:column>` tags.

[discrete]
==== Usage

You can either use a "DOM" source, i.e. any Object with an iterator() method or an "AJAX" source, i.e. using a web service that returns data formatted in JSON.

[source,xml]
----
<datatables:table id="myTableId" data="${myCollection}">
  <datatables:column title="id" property="id" />
  <datatables:column title="firstName" property="firstName" />
  <datatables:column title="LastName" property="lastName" />
  <datatables:column title="City" property="address.town.name" />
  <datatables:column title="Mail" property="mail" />
</datatables:table>
----

Note that:

* you can also use _dynamic attributes_, i.e. attributes that are not officially declared in the TagLib Descriptor. This is convenient especially for all native HTML attributes. 

[source,xml]
----
<datatables:table cellspacing="5">
  ...
</datatables:table>
----

* you can use _expression language_ (EL) in all attributes. 

[source,xml]
----
<datatables:table info="${...}">
  ...
</datatables:table>
----

[discrete]
==== Reference

Note that all options are presented in the following format:

[cols="29,12,59"]
|===
.5+|*Attribute name*
2+|Description of the attribute

_Option_: with which name you can refer to the corresponding feature in the configuration file or n/a otherwise
|Values
|All possible values

|Default
|The default value

|Data source
|With which data source type the attribute is compatible

|Option
|With which name you can refer to the corresponding feature in the configuration file or n/a otherwise

|===

.`<datatables:table>` tag reference
[cols="29,12,59"]
|===

.5+|[[jsp-table-id]]*id*
2+|DOM id of the `<table>` (*_Required_*)

|Values
|Any Java object with an `iterator()` method

|Default	
|

|Data source
|DOM/AJAX

|Option
|n/a

.5+|[[jsp-table-data]]*data*
2+|Java object used to populate the table (*_Either data or url attribute is required_*)

|Values
|Any Java object with an `iterator()` method

|Default
|

|Data source
|DOM

|Option
|n/a

.5+|[[jsp-table-url]]*url*
2+|URL called by DataTables to populate the table. Data returned must be in the JSON format (*_Either data or url attribute is required_*)

|Values
|Any valid URL

|Default
|

|Data source
|AJAX

|Option
|n/a

.5+|[[jsp-table-ajaxParams]]*ajaxParams*
2+|Allows you pass extra AJAX params to the request made agains the server

|Values
|Any String representing the name of an accessible Javascript function. <<14-3-bundle-special-syntax, Bundle special syntax>> allowed.

|Default
|

|Data source
|AJAX

|Option
|n/a

.5+|[[jsp-table-autoWidth]]*autoWidth*
2+|Enable or disable automatic column width calculation

|Values
|true \| false

|Default
|true

|Data source
|DOM/AJAX

|Option
|<<opt-feature.autoWidth,feature.autoWidth>>

.5+|[[jsp-table-confGroup]]*confGroup*
2+|Name of the configuration group to activate in the current table

|Values
|

|Default
|

|Data source
|DOM/AJAX

|Option
|n/a

.5+|[[jsp-table-cssStyle]]*cssStyle*
2+|CSS style to be applied on the `<table>` tag

|Values
|

|Default
|

|Data source
|DOM/AJAX

|Option
|<<opt-css.style,css.style>>

.5+|[[jsp-table-cssClass]]*cssClass*
2+|CSS class(es) to be applied on the `<table>` tag

|Values
|

|Default
|

|Data source
|DOM/AJAX

|Option
|<<opt-css.class,css.class>>

.5+|[[jsp-table-cssStripes]]*cssStripes*
2+|Comma-separated list of CSS classes that should be applied to displayed rows. This sequence of CSS classes may be of any length, and DataTables will apply each class sequentially, looping when required

|Values
|

|Default
|

|Data source
|DOM/AJAX

|Option
|<<opt-css.cssStripes,css.cssStripes>>

.5+|[[jsp-table-deferLoading]]*deferLoading*
2+|Delay the loading of server-side data until second draw

|Values
|Any integer \| Array of integer (length=2)

|Default
|

|Data source
|AJAX

|Option
|<<opt-ajax.deferLoading,ajax.deferLoading>>

.5+|[[jsp-table-deferRender]]*deferRender*
2+|Defer the creation of the table elements for each row until they are needed for a draw

|Values
|true \| false

|Default
|false

|Data source
|AJAX

|Option
|<<opt-ajax.deferRender,ajax.deferRender>>

.5+|[[jsp-table-displayLength]]*displayLength*
2+|Number of rows to display on a single page when using pagination

|Values
|

|Default
|10

|Data source
|DOM/AJAX

|Option
|<<opt-feature.displayLength,feature.displayLength>>

.5+|[[jsp-table-dom]]*dom*
2+|Allows you to specify exactly where in the DOM you want DataTables to inject the various controls it adds to the page

|Values
|See <<4-2-dom-positioning, DOM positioning>>

|Default
|lfrtip

|Data source
|DOM/AJAX

|Option
|<<opt-feature.dom,feature.dom>>

.5+|[[jsp-table-escapeXml]]*escapeXml*
2+|Whether XML characters should be escaped or not

|Values
|true \| false

|Default
|true

|Data source
|DOM/AJAX

|Option
|n/a

.5+|[[jsp-table-export]]*export*
2+|Comma-separated list of enabled export formats. Some formats use reserved words, such as `csv`, `xls`, `xlsx`, `pdf` and `xml`

|Values
|

|Default
|

|Data source
|DOM/AJAX

|Option
|<<opt-export.enabled.formats,export.enabled.formats>>

.5+|[[jsp-table-exportStyle]]*exportStyle*
2+|CSS style to be applied to the container used for export links

|Values
|

|Default
|

|Data source
|DOM/AJAX

|Option 
|<<opt-export.container.style,export.container.style>>

.5+|[[jsp-table-exportClass]]*exportClass*
2+|CSS class(es) to be applied to the container used for export links

|Values
|

|Default
|

|Data source
|DOM/AJAX

|Option
|<<opt-export.container.class,export.container.class>>

.5+|[[jsp-table-ext]]*ext*
2+|Comma-separated names of extensions to register in the current table

|Values
|

|Default
|

|Data source
|DOM/AJAX

|Option
|<<opt-main.extension.names,main.extension.names>>

.5+|[[jsp-table-filterable]]*filterable*
2+|Enable or disable global filtering of data

|Values
|true \| false

|Default
|true

|Data source
|DOM/AJAX

|Option
|<<opt-feature.filterable,feature.filterable>>

.5+|[[jsp-table-filterClearSelector]]*filterClearSelector*
2+|https://api.jquery.com/category/selectors/[jQuery selector] targeting the element on which a 'click' event will be bound to trigger the clearing of all filter elements

|Values
|Any https://api.jquery.com/category/selectors/[jQuery selector]

|Default
|

|Data source
|DOM/AJAX

|Option
|<<opt-feature.filterClearSelector,feature.filterClearSelector>>

.5+|[[jsp-table-filterDelay]]*filterDelay*
2+|Delay (in milliseconds) to be used before the AJAX call is performed to obtain data

|Values
|Any integer

|Default
|500ms

|Data source
|DOM/AJAX

|Option
|<<opt-feature.filterDelay,feature.filterDelay>>

.5+|[[jsp-table-filterPlaceholder]]*filterPlaceholder*
2+|Placeholder used to hold the individual column filtering elements

|Values
|header \| footer \| none

|Default
|footer

|Data source
|DOM/AJAX

|Option
|<<opt-feature.filterPlaceholder,feature.filterPlaceholder>>

.5+|[[jsp-table-filterSelector]]*filterSelector*
2+|https://api.jquery.com/category/selectors/[jQuery selector] targeting the element on which a 'click' event will be bound to trigger the filtering

|Values
|Any https://api.jquery.com/category/selectors/[jQuery selector]

|Default
|

|Data source
|DOM/AJAX

|Option
|<<opt-feature.filterSelector,feature.filterSelector>>

.5+|[[jsp-table-info]]*info*
2+|Enable or disable the table information display. This shows information about the data that is currently visible on the page, including information about filtered data if that action is being performed

|Values
|true \| false

|Default
|true

|Data source
|DOM/AJAX

|Option
|<<opt-feature.info,feature.info>>

.5+|[[jsp-table-fixedPosition]]*fixedPosition*
2+|Respectively fix the header, footer, left column, right column

|Values
|top \| bottom \| left \| right

|Default
|top

|Data source
|DOM/AJAX

|Option
|<<opt-plugin.fixedPosition,plugin.fixedPosition>>

.5+|[[jsp-table-jqueryUI]]*jqueryUI*
2+|Enable jQuery UI ThemeRoller support

|Values
|true \| false

|Default
|false

|Data source
|DOM/AJAX

|Option
|<<opt-feature.jqueryUi,feature.jqueryUi>>

.5+|[[jsp-table-lengthChange]]*lengthChange*
2+|If <<jsp-table-pageable, `pageable`>> is set to true, allows the end user to select the size of a formatted page from a select menu (sizes are 10, 25, 50 and 100)

|Values
|true \| false

|Default
|true

|Data source
|DOM/AJAX

|Option
|<<opt-feature.lengthChange,feature.lengthChange>>

.5+|[[jsp-table-lengthMenu]]*lengthMenu*
2+|Specify the entries in the length drop down menu that DataTables show when pagination is enabled

|Values
|

|Default
|10,25,50,100

|Data source
|DOM/AJAX

|Option
|<<opt-feature.lengthMenu,feature.lengthMenu>>

.5+|[[jsp-table-offsetTop]]*offsetTop*
2+|(<a href="/datatables/features/plugins/fixedheader.html">fixedHeader</a>) Offset applied on the top

|Values
|

|Default
|

|Data source
|DOM/AJAX

|Option
|<<opt-plugin.fixedOffsetTop,plugin.fixedOffsetTop>>

.5+|[[jsp-table-pageable]]*pageable*
2+|Enable or disable pagination

|Values
|true \| false

|Default
|true

|Data source
|DOM/AJAX

|Option
|<<opt-feature.pageable,feature.pageable>>

.5+|[[jsp-table-paginationType]]*pagingType*
2+|Name of the pagination interaction methods which present different page controls to the end user
 
|Values
|simple \| simple_numbers \| full \| full_numbers \| input \| listbox \| scrolling \| extStyle \| bootstrap_simple \| bootstrap_full \| bootstrap_full_numbers

|Default
|simple

|Data source
|DOM/AJAX

|Option
|<<opt-feature.pagingType,feature.pagingType>>

.5+|[[jsp-table-pipelining]]*pipelining*
2+|Enable pipelining data for paging when server-side processing is enabled

|Values
|true \| false

|Default
|false

|Data source
|AJAX

|Option
|<<opt-ajax.pipelining,ajax.pipelining>>

.5+|[[jsp-table-pipeSize]]*pipeSize*
2+|Pipe size used when pipelining is enabled, i.e. times that the user can page before a request must be made of the server

|Values
|Any integer starting from 1

|Default
|5

|Data source
|AJAX

|Option
|<<opt-ajax.pipeSize,ajax.pipeSize>>

.5+|[[jsp-table-processing]]*processing*
2+|Enable or disable the display of a 'processing' indicator when the table is being processed (e.g. a sort). This is particularly useful for tables with large amounts of data where it can take a noticeable amount of time to sort the entries

|Values
|true \| false

|Default
|true

|Data source
|DOM/AJAX

|Option
|<<opt-feature.processing,feature.processing>>

.5+|[[jsp-table-reloadFunction]]*reloadFunction*
2+|Name of a Javascript function that will be called in the 'click' event bound by the reloadSelector attribute. Note that when using this attribute, you will have to call manually the `fnReloadAjax()` function

|Values
|Any String representing the name of an accessible Javascript function. <<14-3-bundle-special-syntax, Bundle special syntax>> allowed.

|Default
|Empty string

|Data source
|AJAX

|Option
|<<opt-ajax.reloadFunction,ajax.reloadFunction>>

.5+|[[jsp-table-reloadSelector]]*reloadSelector*
2+|https://api.jquery.com/category/selectors/[jQuery selector] targeting the element on which a 'click' event will be bound to trigger the table reloading

|Values
|Any https://api.jquery.com/category/selectors/[jQuery selector]

|Default
|Empty string

|Data source
|AJAX

|Option
|<<opt-ajax.reloadSelector,ajax.reloadSelector>>

.5+|[[jsp-table-row]]*row*
2+|Name under which the object representing the current row is added to the pageContext, allowing you to access the object in the body of a `<datatables:column>` tag. If data must be displayed without any decoration, use the <<jsp-column-property, `property`>> attribute of the column tag

|Values
|

|Default
|

|Data source
|DOM

|Option
|

.5+|[[jsp-table-rowIdBase]]*rowIdBase*
2+|Evaluated as a property of the bean being iterated on. The result will be used to apply an ID on each row

|Values
|

|Default
|

|Data source
|DOM

|Option
|

.5+|[[jsp-table-rowIdPrefix]]*rowIdPrefix*
2+|Prefix used to build an ID that will be applied on all table rows. If <<jsp-table-rowIdBase, `rowIdBase`>> is used, the <<jsp-table-rowIdPrefix, `rowIdPrefix`>> is prepended to the <<jsp-table-rowIdBase, `rowIdBase`>>

|Values
|

|Default
|

|Data source
|DOM

|Option
|

.5+|[[jsp-table-rowIdSuffix]]*rowIdSuffix*
2+|Suffix used to build an ID that will be applied on all table rows. If <<jsp-table-rowIdBase, `rowIdBase`>> is used, the <<jsp-table-rowIdSuffix, `rowIdSuffix`>> is appended to the <<jsp-table-rowIdBase, `rowIdBase`>>

|Values
|

|Default
|

|Data source
|DOM

|Option
|

.5+|[[jsp-table-scrollCollapse]]*scrollCollapse*
2+|When vertical (y) scrolling is enabled, DataTables will force the height of the table's viewport to the given height at all times (useful for layout). However, this can look odd when filtering data down to a small data set, and the footer is left "floating" further down. This parameter (when enabled) will cause DataTables to collapse the table's viewport down when the result set will fit within the given Y height.

|Values
|true \| false

|Default
|false

|Data source
|DOM/AJAX

|Option
|<<opt-feature.scrollCollapse,feature.scrollCollapse>>

.5+|[[jsp-table-scrollX]]*scrollX*
2+|Enable horizontal scrolling. When a table is too wide to fit into a certain layout, or you have a large number of columns in the table, you can enable x-scrolling to show the table in a viewport, which can be scrolled

|Values
|Any CSS unit, or a number (in which case it will be treated as a pixel measurement)

|Default
|Empty string, i.e. disabled

|Data source
|DOM/AJAX

|Option
|<<opt-feature.scrollX,feature.scrollX>>

.5+|[[jsp-table-scrollXInner]]*scrollXInner*
2+|Use more width than it might otherwise do when x-scrolling is enabled

|Values
|Any CSS unit, or a number (in which case it will be treated as a pixel measurement)

|Default
|

|Data source
|DOM/AJAX

|Option
|<<opt-feature.scrollXInner,feature.scrollXInner>>

.5+|[[jsp-table-scrollY]]*scrollY*
2+|Enable vertical scrolling. Vertical scrolling will constrain the DataTable to the given height, and enable scrolling for any data which overflows the current viewport. This can be used as an alternative to paging to display a lot of data in a small area (although paging and scrolling can both be enabled at the same time)

|Values
|Any CSS unit, or a number (in which case it will be treated as a pixel measurement)

|Default
|Empty string, i.e. disabled

|Data source
|DOM/AJAX

|Option
|<<opt-feature.scrollY,feature.scrollY>>

.5+|[[jsp-table-serverSide]]*serverSide*
2+|Configure DataTables to use server-side processing. Note that the <<jsp-table-url, `url`>> attribute must be set in order to give DataTables a source to obtain the required data for each draw

|Values
|true \| false

|Default
|false

|Data source
|AJAX

|Option
|<<opt-ajax.serverSide,ajax.serverSide>>

.5+|[[jsp-table-sortable]]*sortable*
2+|Enable or disable sorting of columns. Sorting of individual columns can be disabled by the <<jsp-column-sortable, `sortable`>> attribute of the column tag

|Values
|true \| false

|Default
|true

|Data source
|DOM/AJAX

|Option
|<<opt-feature.sortable,feature.sortable>>

.5+|[[jsp-table-stateSave]]*stateSave*
2+|When enabled a cookie will be used to save table display information such as pagination information, display length, filtering and sorting. As such when the end user reloads the page the display display will match what thy had previously set up

|Values
|true \| false

|Default
|false

|Data source
|DOM/AJAX

|Option
|<<opt-ajax.stateSave,ajax.stateSave>>

.5+|[[jsp-table-theme]]*theme*
2+|Name of a theme to activate for the current table

|Values
|bootstrap2 \| bootstrap3 \| jqueryui

|Default
|

|Data source
|DOM/AJAX

|Option
|<<opt-css.theme,css.theme>>

.5+|[[jsp-table-themeOption]]*themeOption*
2+|Name of an option to activate in relation to the current activated theme

|Values
|See the <<5-3-3-2-available-theme-options, full list of available theme options>>

|Default
|

|Data source
|DOM/AJAX

|Option
|<<opt-css.themeOption,css.themeOption>>

|===

=== A.2. `<datatables:column>` tag

The `<datatables:column>` tag allows you to define the content of a column. 

[discrete]
==== Usage

The `<datatables:column>` tag must be nested within a <<a-1-code-datatables-table-code-tag, `<datatables:table>`>> tag.

You can either let the <<jsp-column-property, `property`>> attribute handle the content of a cell. This attribute allows to access to a bean's property.
   
[source, xml]
---- 
<datatables:table id="myTableId" data="${myCollection}" ...>
  <datatables:column property="aPropertyOfTheBean" ... />
</datatables:table>
----

Or you can set a body and put anything you want inside (HTML code, JSTL tags, Spring tags, ...). See the <<jsp-table-row, `row`>> table attribute which can be particularly useful in this case (compatible with DOM source only)

[source, xml]
---- 
<datatables:table id="myTableId" data="${myCollection}" row="aStringRepresentingTheBean" ...>
  <datatables:column ...>
    <span color="red;">
      <c:out value="${aStringRepresentingTheBean.aPropertyOfTheBean}" />
    </span>
  </datatables:column>
</datatables:table>
----

[discrete]
==== Reference

.`<datatables:column>` tag reference
[cols="29,12,59"]
|===

.4+|[[jsp-column-cssStyle]]*cssStyle*
2+|CSS style to be applied on the header cell of the column (`th`)

|Values
|

|Default
|

|Data source
|DOM/AJAX

.4+|[[jsp-column-cssCellStyle]]*cssCellStyle*
2+|CSS style to be applied on all column cells (`td`)

|Values
|

|Default
|

|Data source
|DOM

.4+|[[jsp-column-cssClass]]*cssClass*
2+|CSS class(es) to be applied on the header cell of the column (`th`)

|Values
|

|Default
|

|Data source
|DOM/AJAX

.4+|[[jsp-column-cssCellClass]]*cssCellClass*
2+|CSS class(es) to be applied on all column cells (`td`)

|Values
|

|Default
|

|Data source
|DOM/AJAX

.4+|[[jsp-column-default]]*default*
2+|Default string to be used if the value returned from the <<jsp-column-property, `property`>> attribute is empty or null

|Values
|

|Default
|Empty string

|Data source
|DOM/AJAX

.4+|[[jsp-column-display]]*display*
2+|Comma-separated list of strings used to filter in which view(s) the column content will be displayed. Not that some strings are reserved:

* 'all': the content will appear both client-side and is all export formats
* 'csv': the content will appear only in the csv export
* 'xls': the content will appear only in the xls export
* 'xlsx': the content will appear only in the xlsx export
* 'pdf': the content will appear only in the pdf export
* 'xml': the content will appear only in the xml export

|Values
|All (HTML and in all export formats)

|Default
|

|Data source
|DOM/AJAX

.4+|[[jsp-column-escapeXml]]*escapeXml*
2+|Whether XML characters should be escaped or not

|Values
|true \| false

|Default
|true

|Data source
|DOM/AJAX

.4+|[[jsp-column-filterable]]*filterable*
2+|Enable or disable filtering in the column. By default, an input field will be created in the tfoot section of the table

|Values
|true \| false

|Default
|false

|Data source
|DOM/AJAX

.4+|[[jsp-column-filterType]]*filterType*
2+|If the column is filterable, configures the filter type

|Values
|select \| input

|Default
|input

|Data source
|DOM/AJAX

.4+|[[jsp-column-filterValues]]*filterValues*
2+|Name of a Javascript variable containing data used to populate the filtering select

|Values
|Either an array of values or an array of objects

|Default
|

|Data source
|DOM/AJAX

.4+|[[jsp-column-format]]*format*
2+|http://docs.oracle.com/javase/6/docs/api/java/text/MessageFormat.html[MessageFormat] pattern that will be used to format the value passed in the <<jsp-column-property, `property`>> attribute

|Values
|Any valid pattern

|Default
|

|Data source
|DOM

.4+|[[jsp-column-id]]*id*
2+|DOM id to be given to the header cell (`th`)

|Values
|

|Default
|

|Data source
|DOM/AJAX

.4+|[[jsp-column-property]]*property*
2+|When using a DOM source, this is the name of the object's attribute of the collection being iterated on. When using an AJAX source, this is the name of the JSON property to be read from the data obtained by the AJAX call

|Values
|

|Default
|

|Data source
|DOM/AJAX

.4+|[[jsp-column-renderFunction]]*renderFunction*
2+|Name of a JavasScript function that will be called to render the column when using an AJAX source

|Values
|Any String representing the name of an accessible Javascript function. <<14-3-bundle-special-syntax, Bundle special syntax>> allowed

|Default
|

|Data source
|AJAX

.4+|[[jsp-column-searchable]]*searchable*
2+|Enable or disable searching in the column. If false, the column won't be filtered by the global search field

|Values
|true \| false

|Default
|true

|Data source
|DOM/AJAX

.4+|[[jsp-column-selector]]*selector*
2+|https://api.jquery.com/category/selectors/[jQuery selector] targeting any element that will be populated with a filtering element (depending on the <<jsp-column-filterType, `filterType`>> attribute). This attribute only makes sense when the <<jsp-column-filterPlaceholder, `filterPlaceholder`>> attribute is set to `none` (i.e. for external filtering form)

|Values
|Any https://api.jquery.com/category/selectors/[jQuery selector]

|Default
|Empty string

|Data source
|DOM/AJAX

.4+|[[jsp-column-sortable]]*sortable*
2+|Enable or disable sorting on column

|Values
|true \| false

|Default
|true

|Data source
|DOM/AJAX

.4+|[[jsp-column-sortDirection]]*sortDirection*
2+|Comma-separated list of directions to be used to control the sorting sequence

|Values
|Comma-separated list of `asc` or `desc` strings

|Default
|

|Data source
|DOM/AJAX

.4+|[[jsp-column-sortInitDirection]]*sortInitDirection*
2+|If the column is sortable, sets the default sorting direction

|Values
|asc  \|  desc

|Default
|asc

|Data source
|DOM/AJAX

.4+|[[jsp-column-sortInitOrder]]*sortInitOrder*
2+|If the column is sortable, sets the order in which the sort should be initialized

|Values
|Any column index (starting from 0)

|Default
|

|Data source
|DOM/AJAX

.4+|[[jsp-column-sortType]]*sortType*
2+|If the column is sortable, configures the type of sort to apply to the column

|Values
|alt_string \| anti_the \| chinese_string \| date_de \| date_eu \| date_euro \| date_uk \| filesize \| ip_address \| natural \| persian \| scientific \| signed_num \| turkish_string
	
|Default
|Type-based, internally guessed by DataTables

|Data source
|DOM/AJAX

.4+|[[jsp-column-title]]*title*
2+|Title to be given to the column (`th` content). Optionnaly, the title can be assigned thanks to the <<jsp-column-titleKey, `titleKey`>> attribute

|Values
|

|Default
|

|Data source
|DOM/AJAX

.4+|[[jsp-column-titleKey]]*titleKey*
2+|Resource key used to lookup the title value in the configured resource bundle

|Value
|

|Default
|

|Data source
|DOM/AJAX

.4+|[[jsp-column-visible]]*visible*
2+|Enable or disable the display of the column. Note that even if the column is not visible, it is searchable

|Values
|true \| false

|Default
|true

|Data source
|DOM/AJAX

|===

=== A.3. `<datatables:columnHead>` tag

The `<datatables:columnHead>` tag allows you to fill in a column header with a more complex content than a simple string.

[discrete]
==== Usage

The `<datatables:columnHead>` tag must be nested within a <<a-2-code-datatables-column-code-tag, `<datatables:column>`>> tag.

[source, xml]
----
<datatables:table id="myTableId" data="${myCollection}" ...>
  <datatables:column>
    <datatables:columnHead>
      <!-- Any content here will appear in the column header... -->
    </datatables:columnHead>
    <!-- Any content here will appear in each cell -->
    </datatables:column>
</datatables:table>
----

[discrete]
==== Reference

This tag has no attribute.

=== A.4. `<datatables:option>` tag

The `<datatables:option>` tag allows you to set a <<appendix-c-configuration-options-reference, configuration option>> in the enclosing table. 

[discrete]
==== Usage

The `<datatables:option>` tag must be nested within a <<a-1-code-datatables-table-code-tag, `<datatables:column>`>> tag.

[source,xml]
----
<datatables:table id="myTableId" data="${myCollection}">
  ...
  <datatables:option name="feature.dom" value="t" />
  ...
</datatables:table>
----

.`<datatables:option>` tag reference
[cols="29,12,59"]
|===
.2+|[[jsp-option-name]]*name*
2+|Name of the <<appendix-c-configuration-options-reference, configuration option>> to be set locally

|Data source
|DOM/AJAX

.2+|[[jsp-option-value]]*value*
2+|Value of the <<appendix-c-configuration-options-reference, configuration option>> to be set locally

|Data source
|DOM/AJAX
|===

=== A.5. `<datatables:export>` tag

Configures a type of export, e.g. allowing to apply CSS on export links.

[discrete]
==== Usage

The `<datatables:export>` tag must be nested within a `<datatables:table>` tag.

[source, xml]
----
<datatables:table ... export="pdf,xls"> <1>
   ...
   <datatables:export type="pdf" cssClass="btn btn-info" />
   <datatables:export type="xls" cssClass="btn btn-success" />
   ...
</datatables:table>
----
<1> Note that an export must be enabled using the <<jsp-table-export, `export`>> table attribute before being able to configure it

[discrete]
==== Reference

.`<datatables:export>` tag reference
[cols="29,12,59"]
|===
.4+|[[jsp-option-name]]*name*
2+|Name of the <<appendix-c-configuration-options-reference, configuration option>> to be set locally

|Values
|Any valid <<appendix-c-configuration-options-reference, option name>>

|Default
|

|Data source
|DOM/AJAX


.4+|[[jsp-export-type]]*type*
2+|Type of export to configure (*_Required_*)

|Values
|Must match one of the value set in the <<jsp-table-export, `export`>> table attribute

|Default
|

|Data source
|DOM/AJAX

.4+|[[jsp-export-label]]*label*
2+|Label to be applied to the export link

|Values
|Any string

|Default
|The upper-cased value of the <<jsp-export-type, `type`>> export attribute

|Data source
|DOM/AJAX

.4+|[[jsp-export-cssStyle]]*cssStyle*
2+|CSS style to be applied to the export link. (HTML pass through attribute)

|Values
|One or more CSS properties and values separated by semicolons

|Default
|

|Data source
|DOM/AJAX

.4+|[[jsp-export-cssClass]]*cssClass*
2+|CSS class(es) to be applied to the export link. (HTML pass through attribute)

|Values
|

|Default
|

|Data source
|DOM/AJAX

.4+|[[jsp-export-includeHeader]]*includeHeader*
2+|Whether header cells (`<th>`) should appear in the export file or not

|Values
|true \| false

|Default
|true

|Data source
|DOM/AJAX

.4+|[[jsp-export-fileName]]*fileName*
2+|Name to be given to the exported file (without extension)

|Values
|Any string

|Default
|[exportType-upperCased]-[yyyymmDD]

|Data source
|DOM/AJAX

.4+|[[jsp-export-fileName]]*fileExtension*
2+|File extension of the exported file. Note that if reserved words are used, the file extension will be automatically set

|Values
|Any string

|Default
|The lower-cased value of the <<jsp-export-type, `type`>> export attribute

|Data source
|DOM/AJAX

.4+|[[jsp-export-autoSize]]*autoSize*
2+|Whether columns should be autosized in the export file

|Values
|true \| false

|Default
|true

|Data source
|DOM/AJAX

.4+|[[jsp-export-url]]*url*
2+|URL to be used for exporting. Handy if you want to customize exports using controllers. When no `url` attribute is used, Dandelion-Datatables generates an internal URL for export processing. Note that the URL is internally processed by prepending the request context path and appending all current URL parameters

|Values
|true \| false

|Default
|true

|Data source
|DOM/AJAX

.4+|[[jsp-export-method]]*method*
2+|HTTP method to be used when performing the export call when the <<jsp-export-url, `url`>> export attribute is used

|Values
|Any valid HTTP method

|Default
|GET

|Data source
|DOM/AJAX

.4+|[[jsp-export-orientation]]*orientation*
2+|Orientation of the export file (PDF only)

|Values
|landscape \| portrait

|Default
|landscape

|Data source
|DOM/AJAX

.4+|[[jsp-export-mimeType]]*mimeType*
2+|Mime type applied to the response when downloading the export file. Note that if one of the reserved words is used, the mime type will be automatically set

|Values
|

|Default
|

|Data source
|DOM/AJAX

.4+|[[jsp-export-escapeXml]]*escapeXml*
2+|Whether XML characters should be escaped or not

|Values
|true \| false

|Default
|true

|Data source
|DOM/AJAX
|===

=== A.6. `<datatables:callback>` tag

The `<datatables:callback>` tag allows you to configure one or multiple DataTables callbacks in the table.

[discrete]
==== Usage

The `<datatables:callback>` tag must be nested within a `<datatables:table>` tag.

[source, xml]
----
<datatables:table>
  ...
  <datatables:callback type="..." function="..." />
  ...
</datatables:table>
----

See the <<7-3-using-callbacks, callback section>> for more details. 

[discrete]
==== Reference

.`<datatables:callback>` tag reference
[cols="29,12,59"]
|===
.4+|[[jsp-callback-type]]*type*
2+|Type of the callback (*_Required_*)

|Values
|createdrow \| draw \| footer \| format \| header \| info \| init \| predraw \| row \| statesave \| statesaveparams \| stateload \| stateloadparams \| stateloaded

|Default
|

|Data source
|DOM/AJAX

.4+|[[jsp-callback-function]]*function*
2+|Name of a JavaScript function that will be called inside the configured callback (*_Required_*)

|Values
|Any String representing the name of an accessible JavaScript function. <<14-3-bundle-special-syntax, Bundle special syntax>> allowed.

|Default
|

|Data source
|DOM/AJAX
|===

=== A.7. `<datatables:extraJs>` tag

Specify the location of an extra file containing JavaScript code which will be merged with the main JavaScript generated file.

[discrete]
==== Usage

The `<datatables:extraJs>` tag must be nested within a `<datatables:table>` tag.

[source, xml]
----
<datatables:table>
  ...
  <datatables:extraJs bundles="bundle1" />
  ...
</datatables:table>
----

See the <<7-1-using-extra-javascript, extra JavaScript section>> for more details. 

[discrete]
==== Reference

.`<datatables:extraJs>` tag reference
[cols="29,12,59"]
|===
.4+|[[jsp-extraJs-bundles]]*bundles*
2+|Comma-separated list of bundle to include in the current request (*_Required_*)

|Values
|

|Default
|

|Data source
|DOM/AJAX

.4+|[[jsp-extraJs-insert]]*insert*
2+|Location where extra file content will be inserted into the generated configuration

|Values
|beforeall \| beforestartdocumentready \| afterstartdocumentready \| beforeenddocumentready \| afterall

|Default
|BEFOREALL

|Data source
|DOM/AJAX
|===

=== A.8. `<datatables:extraHtml>` tag

The `<datatables:extraHtml>` tag allows you to create a HTML snippet that will be used as a https://datatables.net/manual/plug-ins/features[DataTables feature plug-in].

Once created, the snippet must be activated thanks to <<jsp-table-dom, `dom`>> table attribute.

[discrete]
==== Usage

The `<datatables:extraHtml>` tag must be nested within a `<datatables:table>` tag.

[source, xml]
----
<datatables:table id="myTableId" data="${persons}" dom="l0frtip">
  ...
  <datatables:extraHtml uid="0" cssStyle="float:right; margin-left: 5px;">
    <a class="btn" onclick="alert('Click!');">My custom link</a>
  </datatables:extraHtml>
  ...
</datatables:table>
----

See the <<_7_2_using_extra_html_snippets, extra HTML snippets section>> for more information. 

[discrete]
==== Reference

.`<datatables:extraHtml>` tag reference
[cols="29,12,59"]
|===
.4+|[[jsp-extraHtml-uid]]*uid*
2+|The identifying character to be assigned to the HTML snippet. Once the HTML snippet created, it must be activated thanks to the <<jsp-table-dom, `dom`>> table attribute. See the <<7-2-using-extra-html-snippets, extra HTML snippets section>> (*_Required_*)

|Values
|Any figure between 0 and 9 is recommended

|Default
|

|Data source
|DOM/AJAX

.4+|[[jsp-extraHtml-cssStyle]]*cssStyle*
2+|CSS style to be applied to the container of the extra HTML snippet

|Values
|

|Default
|

|Data source
|DOM/AJAX

.4+|[[jsp-extraHtml-cssClass]]*cssClass*
2+|CSS class(es) to be applied to the container of the extra HTML snippet

|Values
|

|Default
|

|Data source
|DOM/AJAX

.4+|[[jsp-extraHtml-container]]*container*
2+|Container used to wrap the extra HTML snippet

|Values
|Any valid HTML element

|Default
|div

|Data source
|DOM/AJAX

.4+|[[jsp-extraHtml-escapeXml]]*escapeXml*
2+|Whether XML characters should be escaped or not

|Values
|true \| false

|Default
|true

|Data source
|DOM/AJAX
|===
