== 6. Styling

There are a number of ways in which DataTables allows you to style tables and HTML it adds to the document. Dandelion-DataTables supports some of them but also provides themes integration for Bootstrap or jQueryUI.
	
=== 6.1. Basics

Both JSP taglib and Thymeleaf dialect provide attributes that can style different elements: the table, the row, header cells, ...

The table below lists all possibilities.

.Available attributes
|===
|Applies to |JSP |Thymeleaf |Description

|the table (`<table>` element)
|<<jsp-table-cssStyle, `cssStyle`>> / <<jsp-table-cssClass, `cssClass`>>
|`style` / `class` (native HTML attributes)
|Inlined style or CSS class(es)

|the rows (`<tr>` elements)
|<<jsp-table-cssStripes, `cssStripes`>>
|<<tml-table-stripeClasses, `dt:stripeClasses`>>
|Sequence of CSS classes that will be selected sequentially, looping when required

|the header cells (`<th>` elements)
|<<jsp-column-cssStyle, `cssStyle`>> / <<jsp-column-cssClass, `cssClass`>>
|`style` / `class` (native HTML attributes)
|Applies style or CSS class(es)

|all other cells (`<td>` elements)
|<<jsp-column-cssCellStyle, `cssCellStyle`>> / <<jsp-column-cssCellClass, `cssCellClass`>>
|<<tml-table-stripeClasses, `dt:stripeClasses`>>
|`style` / `class` (native HTML attributes)
|===

[discrete]
==== Example using JSP

[source, xml]
----
<datatables:table id="myTableId" data="${persons}" cssClass="myClass" cssStripes="myOdd,myEven"> <1> <2>
  <datatables:column title="Id" property="id" cssClass="myColumn1Class" /> <3>
  <datatables:column title="FirstName" property="firstName" />
  <datatables:column title="LastName" property="lastName" />
  <datatables:column title="Mail" property="mail" />
</datatables:table>
----
<1> `myClass` will be applied to the `<table>` element
<2> `customOdd` and `customEven` will be applied to each row sequentially
<3> `myColumn1Class` will be applied to the header cell of the 1st column

[discrete]
==== Example using Thymeleaf

Since the Thymeleaf syntax is based on pure HTML, most of the previous attributes are natively available in HTML.

[source, html]
----
<table id="myTableId" dt:table="true" class="myClass" dt:stripeClasses="myOdd,myEven"> <1> <2>
  <thead>
    <tr>
      <th class="myColumn1Class">Id</th> <3>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Mail</th>
    </tr>
  </thead>
  ...
</table>
----
<1> `myClass` will be applied to the `<table>` element
<2> `customOdd` and `customEven` will be applied to each row sequentially
<3> `myColumn1Class` will be applied to the header cell of the 1st column

=== 6.2. Using external styles

DataTables will add a number of elements to the page, each with a suitable default ID and/or class to allow CSS selectors to address the element.

You will find below the reference of the id's and classes applied to HTML elements added by DataTables and Dandelion-Datatables:

|===
|Feature |Information |ID |Class(es)

|Processing indicator
|By default inserted before the table (can be changed by using the {% refjsp dt table dom %} table attribute)
|*_processing
|dataTables_processing

|Change display length
|By default inserted before the table (can be changed by using the {% refjsp dt table dom %} table attribute)
|*_length
|dataTables_length

|Filter
|By default inserted before the table (can be changed by using the {% refjsp dt table dom %} table attribute)
|*_filter
|dataTables_filter

|Pagination
|By default inserted after the table (can be changed by using the {% refjsp dt table dom %} table attribute)
|*_paginate
|dataTables_paginate

|Pagination
|
|*_previous
|paginate_disabled_previous <br> paginate_enabled_previous

|Pagination
|
|*_next
|paginate_disabled_next <br> paginate_enabled_next

|Display information
|By default inserted after the table (can be changed by using the {% refjsp dt table dom %} table attribute)
|*_info
|dataTables_info

|Sorting (headers)
|Applied to the TH in the table header if no sort direction is being applied
|
|sorting

|Sorting (headers)
|Applied to the TH in the table header if a sort direction has been applied
|
|sorting_asc <br> sorting_desc

|Sorting (headers)
|Applied to the TH in the table header if sorting is disabled
|
|sorting_asc_disabled <br> sorting_desc_disabled

|Sorting (columns)
|Applied to the TD's in the column which is being sorted upon. The '_1', '_2' and '_3' prefix is applied for multi-column sorting in priority order
|
|sorting_1
sorting_2
sorting_3

|General
|General wrapper div element around the table
|*_wrapper
|dataTables_wrapper

|Zero records found cell
|This class name is applied to the table cell which reports that 'zero records' have been found. This cell is dynamically created by DataTables, so this class is applied to allow extra styling
|
|dataTables_empty

|Export
|This class name is applied to all export div element (those containing export links)
|
|dandelion_dataTables_export
|===

=== 6.3. Theming

Themes are handy to customize your tables and pretty easy to activate: use the <<jsp-table-theme, `theme`>> (JSP) / <<tml-table-theme, `dt:theme`>> (Thymeleaf) table attributes. 

All of them cover pretty much the same actions:

* pull required assets, using the embedded vendor bundles
* add/remove DataTable's parameters (such as the paging control) to adapt to the current theme

==== 6.3.1. Bootstrap 2

===== Using JSP

[source, xml]
----
<datatables:table id="myTableId" data="${persons}" theme="bootstrap2" cssClass="table table-striped">
  ...
</datatables:table>
----

===== Using Thymeleaf

[source, html]
----
<table id="myTableId" dt:table="true" dt:theme="bootstrap2" class="table table-striped">
  ...
</table>
----

TIP: Note that Bootstrap classes such as `table` or `table-striped` need to be added manually

Moreover, since the v0.9.1, you can additionally apply some theme options to the BS2 theme, thanks to https://github.com/bwsewell/tablecloth[tablecloth].

In order to activate this theme option:

* Set the <<jsp-table-themeOption, `themeOption`>> (JSP) / <<tml-table-themeOption, `dt:themeOption`>> (Thymeleaf) table attribute to `tablecloth`
* Add a CSS class among: `table-dark`, `table-stats` or `table-paper`

===== Using JSP

[source, xml]
----
<datatables:table ... theme="bootstrap2" themeOption="tablecloth" cssClass="table table-dark">
  ...
</datatables:table>
----

===== Using Thymeleaf

[source, html]
----
<table ... dt:theme="bootstrap2" dt:themeOption="tablecloth" class="table table-dark">
  ...
</table>
----

<h3 class="section-title" id="mytr">Making your table responsive</h3>
<p>
   Starting from the v0.10.0, an extension based on
   <a href="https://github.com/Comanche/datatables-responsive">datatables-responsible</a>,
   authored by <a href="https://github.com/Comanche">Comanche</a>, has
   been added, allowing you to add a responsibe behaviour to your tables.
</p>
<p>
   To enable a responsive behaviour, you need:
</p>
<ol>
   <li>To activate the <i>datatables-responsive</i> extension using the
      {% refjsp dt table ext%} (JSP) / {% reftl dt table ext %}
      (Thymeleaf) table attribute.
   </li>
   <li>Add some data-* attributes to the table elements:
      <ul>
         <li>Add the <code>data-class="expand"</code> attribute to
            the <code>th</code> element for the respective column that
            will you want to display the expand icon in. The th element
            cannot be for a column that will be hidden.
         </li>
         <li>Add <code>data-hide="phone,tablet"</code> to the <code>th</code>
            element for the respective column that will you want to hide
            when the window is resized.
         </li>
         <li>Add <code>data-name="Hidden Column Name"</code> to the
            <code>th</code> element for the respective column that will
            you would like its label to be set to when hidden.
         </li>
      </ul>
   </li>
</ol>
<p>
   That's all!
</p>

<h4>Example using JSP</h4>
<pre class="prettyprint">
<datatables:table id="myTableId" data="${persons}" theme="bootstrap2" ext="bootstrap2-responsive" cssClass="table table-striped table-bordered">
   <datatables:column title="Id" property="id" data-class="expand" />
   <datatables:column title="FirstName" property="firstName" />
   <datatables:column title="LastName" property="lastName" />
   <datatables:column title="Street" property="address.town.name" data-hide="phone,tablet" />
   <datatables:column title="Mail" property="mail" data-hide="phone,tablet" />
</datatables:table>
</pre>

<h4>Example using Thymeleaf</h4>
<pre class="prettyprint">
<table id="myTableId" dt:table="true" dt:theme="bootstrap2" class="table table-striped table-bordered" dt:ext="bootstrap2-responsive">
   <thead>
      <tr>
         <th data-class="expand">Id</th>
         <th>LastName</th>
         <th>FirstName</th>
         <th data-hide="phone,tablet">City</th>
         <th data-hide="phone,tablet">Mail</th>
      </tr>
   </thead>
   <tbody>
      <tr th:each="person : ${persons}">
         <td th:text="${person?.id}">1</td>
         <td th:text="${person?.lastName}">Doe</td>
         <td th:text="${person?.firstName}">John</td>
         <td th:text="${person?.address?.town?.name}">Nobody knows!</td>
         <td th:text="${person?.mail}">john@doe.com</td>
      </tr>
   </tbody>
</table>
</pre>

==== 6.3.2. Bootstrap 3

<p>
   Dandelion-Datatables provides an easy way to apply the
   <a href="http://getbootstrap.com/">Bootstrap framework</a> (v3)
   on your tables.
</p>

<h3 class="section-title" id="atb3t">Activating the Bootstrap 3 theme</h3>
<p>
   Just follow these steps:
</p>
<ol>
   <li><i>Use the JSP taglib / Thymeleaf dialect</i>
      <p>
         Set the {% refjsp dt table theme %} (JSP) / {% reftl dt table theme %} (Thymeleaf) table attribute to <code>bootstrap3</code>.
      </p>
   </li>
   <li><i>Use the Bootstrap classes</i>
      <p>
         At least, you need to add the
         <code>table</code>
         CSS class. But you can use any of the other CSS classes
         provided by Bootstrap:
         <code>table-striped</code>
         ,
         <code>table-bordered</code>
         , ...
      </p>
      <p>
         Just use the {% refjsp dt table cssClass %} table attribute of
         the JSP taglib, or simply the
         <code>class</code>
         table attribute when using Thymeleaf.
      </p>
   </li>
</ol>

<h3 class="section-title" id="ex">Example</h3>
<h4>Using JSP</h4>
<pre class="prettyprint">
<datatables:table id="myTableId" data="${persons}" theme="bootstrap3" cssClass="table table-striped">
   <datatables:column title="Id" property="id" />
   <datatables:column title="FirstName" property="firstName" />
   <datatables:column title="LastName" property="lastName" />
   <datatables:column title="Street" property="address.town.name" />
   <datatables:column title="Mail" property="mail" />
</datatables:table>
</pre>

<h4>Using Thymeleaf</h4>
<pre class="prettyprint">
<table id="myTableId" dt:table="true" dt:theme="bootstrap3" class="table table-striped">
   <thead>
      <tr>
         <th>Id</th>
         <th>Firstname</th>
         <th>Lastname</th>
         <th>Street</th>
         <th>Mail</th>
      </tr>
   </thead>
   <tbody>
      <tr th:each="person : ${persons}">
         <td th:text="${person?.id}">1</td>
         <td th:text="${person?.firstName}">John</td>
         <td th:text="${person?.lastName}">Doe</td>
         <td th:text="${person?.address?.town?.name}">Nobody knows !</td>
         <td th:text="${person?.mail}">john@doe.com</td>
      </tr>
   </tbody>
</table>
</pre>


<h3 class="section-title" id="mytr">Making your table responsive</h3>
<p>
   Starting from the v0.10.0, an extension based on
   <a href="https://github.com/Comanche/datatables-responsive">datatables-responsible</a>,
   authored by <a href="https://github.com/Comanche">Comanche</a>, has
   been added, allowing you to add a responsibe behaviour to your tables.
</p>
<p>
   To enable a responsive behaviour, you need:
</p>
<ol>
   <li>To activate the <i>datatables-responsive</i> extension using the
      {% refjsp dt table ext%} (JSP) / {% reftl dt table ext %}
      (Thymeleaf) table attribute.
   </li>
   <li>Add some data-* attributes to the table elements:
      <ul>
         <li>Add the <code>data-class="expand"</code> attribute to
            the <code>th</code> element for the respective column that
            will you want to display the expand icon in. The th element
            cannot be for a column that will be hidden.
         </li>
         <li>Add <code>data-hide="phone,tablet"</code> to the <code>th</code>
            element for the respective column that will you want to hide
            when the window is resized.
         </li>
         <li>Add <code>data-name="Hidden Column Name"</code> to the
            <code>th</code> element for the respective column that will
            you would like its label to be set to when hidden.
         </li>
      </ul>
   </li>
</ol>
<p>
   That's all!
</p>

<h4>Example using JSP</h4>
<pre class="prettyprint">
<datatables:table id="myTableId" data="${persons}" theme="bootstrap3" ext="bootstrap3-responsive" cssClass="table table-striped table-bordered">
   <datatables:column title="Id" property="id" data-class="expand" />
   <datatables:column title="FirstName" property="firstName" />
   <datatables:column title="LastName" property="lastName" />
   <datatables:column title="Street" property="address.town.name" data-hide="phone,tablet" />
   <datatables:column title="Mail" property="mail" data-hide="phone,tablet" />
</datatables:table>
</pre>

<h4>Example using Thymeleaf</h4>
<pre class="prettyprint">
<table id="myTableId" dt:table="true" dt:theme="bootstrap3" class="table table-striped table-bordered" dt:ext="bootstrap3-responsive">
   <thead>
      <tr>
         <th data-class="expand">Id</th>
         <th>LastName</th>
         <th>FirstName</th>
         <th data-hide="phone,tablet">City</th>
         <th data-hide="phone,tablet">Mail</th>
      </tr>
   </thead>
   <tbody>
      <tr th:each="person : ${persons}">
         <td th:text="${person?.id}">1</td>
         <td th:text="${person?.lastName}">Doe</td>
         <td th:text="${person?.firstName}">John</td>
         <td th:text="${person?.address?.town?.name}">Nobody knows!</td>
         <td th:text="${person?.mail}">john@doe.com</td>
      </tr>
   </tbody>
</table>
</pre>

==== 6.3.3. jQuery UI

<p>
   Dandelion-Datatables provides an easy way to apply the
   <a href="http://jqueryui.com/themeroller/">ThemeRoller</a> themes
   from <a href="http://jqueryui.com/">jQueryUI</a>.
</p>

<h3 class="section-title" id="atjquit">Activating the jQuery UI theme</h3>
<p>
   Just follow these steps:
</p>
<ol>
   <li><i>Use the JSP taglib / Thymeleaf dialect</i>
      <p>
         Set the {% refjsp dt table theme %} (JSP) / {% reftl dt table theme %} (Thymeleaf) table attribute to
         <code>jqueryui</code>
         .
      </p></li>
   <li><i>Choose a theme option</i>
      <p>
         Use the {% refjsp dt table themeOption %} (JSP) / {% reftl dt table dt:themeOption %} (Thymeleaf) table attributes to select
         a theme option. See <a
            href="/datatables/docs/ref/configuration/#themeoptions">full
            list</a> of available values.
      </p></li>
</ol>

<h3 class="section-title" id="ex">Example</h3>
<h4>Using JSP</h4>

[source, xml]
----
<datatables:table id="myTableId" data="${persons}" theme="jqueryui" themeOption="blacktie">
  ...
</datatables:table>
----

<h4>Using Thymeleaf</h4>

[source, html]
----
<table id="myTableId" dt:table="true" dt:theme="jqueryui" themeOption="blacktie">
   ...
</table>
----
