== 5. Styling

There are a number of ways in which DataTables allows you to style tables and HTML it adds to the document. Dandelion-DataTables supports some of them but also provides themes integration for Bootstrap or jQueryUI.
	
=== 5.1. Basics

Both JSP taglib and Thymeleaf dialect provide attributes that can style different elements: the table, the row, header cells, ...

The table below lists all possibilities.

.Available attributes
|===
|Applies to |JSP |Thymeleaf |Description

|the table (`<table>` element)
|<<jsp-table-cssStyle, `cssStyle`>> / <<jsp-table-cssClass, `cssClass`>>
|`style` / `class` (native HTML attributes)
|Inlined style or CSS class(es)

|the rows (`<tr>` elements)
|<<jsp-table-cssStripes, `cssStripes`>>
|<<tml-table-stripeClasses, `dt:stripeClasses`>>
|Sequence of CSS classes that will be selected sequentially, looping when required

|the header cells (`<th>` elements)
|<<jsp-column-cssStyle, `cssStyle`>> / <<jsp-column-cssClass, `cssClass`>>
|`style` / `class` (native HTML attributes)
|Applies style or CSS class(es)

|all other cells (`<td>` elements)
|<<jsp-column-cssCellStyle, `cssCellStyle`>> / <<jsp-column-cssCellClass, `cssCellClass`>>
|<<tml-table-stripeClasses, `dt:stripeClasses`>>
|`style` / `class` (native HTML attributes)
|===

[discrete]
==== Example using JSP

[source, xml]
----
<datatables:table id="myTableId" ... cssClass="myClass" cssStripes="myOdd,myEven"> <1> <2>
  <datatables:column title="Id" property="id" cssClass="myColumn1Class" /> <3>
  ...
</datatables:table>
----
<1> `myClass` will be applied to the `<table>` element
<2> `customOdd` and `customEven` will be applied to each row sequentially
<3> `myColumn1Class` will be applied to the header cell of the 1st column

[discrete]
==== Example using Thymeleaf

Since the Thymeleaf syntax is based on pure HTML, most of the previous attributes are natively available in HTML.

[source, html]
----
<table id="myTableId" dt:table="true" class="myClass" dt:stripeClasses="myOdd,myEven"> <1> <2>
  <thead>
    <tr>
      <th class="myColumn1Class">Id</th> <3>
      ...
    </tr>
  </thead>
  ...
</table>
----
<1> `myClass` will be applied to the `<table>` element
<2> `customOdd` and `customEven` will be applied to each row sequentially
<3> `myColumn1Class` will be applied to the header cell of the 1st column

=== 5.2. Using external styles

DataTables will add a number of elements to the page, each with a suitable default ID and/or class to allow CSS selectors to address the element.

You will find below the reference of the id's and classes applied to HTML elements added by DataTables and Dandelion-Datatables:

|===
|Feature |Information |ID |Class(es)

|Processing indicator
|By default inserted before the table (can be changed by using the <<jsp-table-dom, `dom`>>/<<tml-table-dom, `dt:dom`>> table attribute)
|*_processing
|dataTables_processing

|Change display length
|By default inserted before the table (can be changed by using the <<jsp-table-dom, `dom`>>/<<tml-table-dom, `dt:dom`>> table attribute)
|*_length
|dataTables_length

|Filter
|By default inserted before the table (can be changed by using the <<jsp-table-dom, `dom`>>/<<tml-table-dom, `dt:dom`>> table attribute)
|*_filter
|dataTables_filter

|Pagination
|By default inserted after the table (can be changed by using the <<jsp-table-dom, `dom`>>/<<tml-table-dom, `dt:dom`>> table attribute)
|*_paginate
|dataTables_paginate

|Pagination
|
|*_previous
|paginate_disabled_previous
paginate_enabled_previous

|Pagination
|
|*_next
|paginate_disabled_next
paginate_enabled_next

|Display information
|By default inserted after the table (can be changed by using the <<jsp-table-dom, `dom`>>/<<tml-table-dom, `dt:dom`>> table attribute)
|*_info
|dataTables_info

|Sorting (headers)
|Applied to the `th` in the table header if no sort direction is being applied
|
|sorting

|Sorting (headers)
|Applied to the `th` in the table header if a sort direction has been applied
|
|sorting_asc
sorting_desc

|Sorting (headers)
|Applied to the `th` in the table header if sorting is disabled
|
|sorting_asc_disabled
sorting_desc_disabled

|Sorting (columns)
|Applied to the TD's in the column which is being sorted upon. The '_1', '_2' and '_3' prefix is applied for multi-column sorting in priority order
|
|sorting_1
sorting_2
sorting_3

|General
|General wrapper div element around the table
|*_wrapper
|dataTables_wrapper

|Zero records found cell
|This class name is applied to the table cell which reports that 'zero records' have been found. This cell is dynamically created by DataTables, so this class is applied to allow extra styling
|
|dataTables_empty

|Export
|This class name is applied to all export div element (those containing export links)
|
|dandelion_dataTables_export
|===

=== 5.3. Theming

Themes are handy to customize your tables and pretty easy to activate: use the <<jsp-table-theme, `theme`>> (JSP) / <<tml-table-theme, `dt:theme`>> (Thymeleaf) table attributes. 

All of them cover pretty much the same actions:

* pull required assets, using the embedded vendor bundles
* add/remove DataTable's parameters (such as the paging control) to adapt to the current theme

==== 5.3.1. Bootstrap 2

[discrete]
===== Using JSP

[source, xml]
----
<datatables:table id="myTableId" ... theme="bootstrap2" cssClass="table table-striped">
  ...
</datatables:table>
----

[discrete]
===== Using Thymeleaf

[source, html]
----
<table id="myTableId" dt:table="true" dt:theme="bootstrap2" class="table table-striped">
  ...
</table>
----

TIP: Note that Bootstrap classes such as `table` or `table-striped` need to be added manually

==== 5.3.2. Bootstrap 3

[discrete]
===== Using JSP

[source, xml]
----
<datatables:table id="myTableId" ... theme="bootstrap3" cssClass="table table-striped">
  ...
</datatables:table>
----

[discrete]
===== Using Thymeleaf

[source, html]
----
<table id="myTableId" dt:table="true" ... dt:theme="bootstrap3" class="table table-striped">
  ...
</table>
----

TIP: Note that Bootstrap classes such as `table` or `table-striped` need to be added manually

==== 5.3.3. jQuery UI

Dandelion-Datatables provides an easy way to apply the http://jqueryui.com/themeroller/[ThemeRoller] themes from http://jqueryui.com/[jQueryUI].

===== 5.3.3.1. Activating the jQuery UI theme

Follow these steps:

. _Use the JSP taglib / Thymeleaf dialect_

+
Set the <<jsp-table-theme, `theme`>> (JSP) / <<tml-table-theme, `dt:theme`>> (Thymeleaf) table attribute to `jqueryui`

. _Choose a theme option_

+
Use the <<jsp-table-themeOption, `themeOption`>> (JSP) / <<tml-table-themeOption, `dt:themeOption`>> (Thymeleaf) table attributes to select a theme option. See full list of available theme options in the next section.

[discrete]
===== Using JSP

[source, xml]
----
<datatables:table id="myTableId" ... theme="jqueryui" themeOption="blacktie">
  ...
</datatables:table>
----

[discrete]
===== Using Thymeleaf

[source, html]
----
<table id="myTableId" dt:table="true" ... dt:theme="jqueryui" themeOption="blacktie">
   ...
</table>
----

===== 5.3.3.2. Available theme options

Below is a list of all available theme options for the jQueryUI theme: 

* `blacktie`
* `blitzer`
* `cupertino`
* `darkhive`
* `dotluv`
* `eggplant`
* `excitebike`
* `flick`
* `hotsneaks`
* `humanity`
* `lefrog`
* `mintchoc`
* `overcast`
* `peppergrinder`
* `redmond`
* `smoothness`
* `southstreet`
* `start`
* `sunny`
* `swankypurse`
* `trontastic`
* `uidarkness`
* `uilightnes`
* `vader`

